### ISSUE TITLE
[SPFX ListCommandSet] _onListViewStateChanged event will never trigger if it is in grouped list view and this group has only one item

### ISSUE THREAD

**Issue by wuxiaojun514** [SharePoint/sp-dev-docs#10047]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx 1.19 version  (I tried to create a helloworld list commandset with 1.20, it never load in new list UI...)
- Node.js version
- etc

### Describe the bug / error

I guess this issue maybe related with #9944 

We have a spfx list command set with a customized button
Like this screenshot
![image](https://github.com/user-attachments/assets/e66916c1-15fb-47f5-b514-73e50ea01c09)

This week we suddenly find it doesn't work (button doesn't show) in grouped list view when there is only one item in this group
![image](https://github.com/user-attachments/assets/d1b127d3-441b-4b57-b3fd-6da91a909f52)
For example, if there is only one pending item in "Approve/Reject" view, then our customized button will never appear.

I debugged the code and find `_onListViewStateChanged` event will **never trigger** if there is only one row in group on grouped list view.
![image](https://github.com/user-attachments/assets/2b59efc9-81bc-443c-b9dd-19bfc78ca13d)

I saw there is closed similar issue #7794 but that one is not for new list UI.

### Steps to reproduce

1. Create a list view commandset extension as https://learn.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api said (why this sample page still use the deprecated `public onListViewUpdated(event: IListViewCommandSetListViewUpdatedParameters): void` method as example?)
2. Run this spfx extension on a list which has grouped list view (You can just enable approval on this list, then you will get "approve/reject items" view which group by approval status
3. You will find that the "Command One" button will never appear if you have only item in the group

### Expected behavior

The _onListViewStateChanged event in List View CommandSet Extension should work as expected in grouped list view

**Comment by Feets20** [comment]
We're seeing issues with this as well. This seemed to be fixed / working for a while and then noticed this week it stopped working

**Comment by VesaJuvonen** [comment]
@reedpamsft something on the list experiences with SPFx

**Comment by reedpamsft** [comment]
@VesaJuvonen @wuxiaojun514 @Feets20   thanks!  Feets20 reported this on the other thread and we're looking into it.

**Comment by reedpamsft** [comment]
@VesaJuvonen @wuxiaojun514 @Feets20  we have a fix for this which will roll out with new client builds in January; eta the week of the 13th.  Emphasis on "estimated", though.  The first build of a new year is often delayed.

**Comment by Haiqi-Wu** [comment]
I'm facing a similar issue, with a slight difference that when I go to the list page, expand the group, and check the item for the first time it doesn't trigger the listViewStateChangedEvent, this is the first case; in the second case, when I go to the page, expand the group, and check all the items under the group through the multi-checkboxes in the group it doesn't trigger the listViewStateChangedEvent.
![image](https://github.com/user-attachments/assets/c495c77b-b981-4e3b-82fd-87db53823184)
![image](https://github.com/user-attachments/assets/98a7e133-f49b-4db3-84c6-9bfdf5aa6dc9)


And we use SharePoint Online, which is operated by 21v.

**Comment by wuxiaojun514** [comment]
Hi @Haiqi-Wu , 
I have the same experience for the first case you found, it won't trigger the event in grouped by view until you choose item again.
I remembered this behavior occurs long time ago.

**Comment by Haiqi-Wu** [comment]
@reedpamsft  Will the fix roll out this week?

**Comment by Haiqi-Wu** [comment]
Looks like it's fixed.

**Comment by wuxiaojun514** [comment]
Yes, it works for me now.
Many thanks!
I will close this ticket.

**Comment by Feets20** [comment]
@reedpamsft Was anything rolled back recently? I saw this was working fine yesterday and today it appears to be behaving how it did before

**Comment by reedpamsft** [comment]
@Feets20 unfortunately, the fix for this issue caused https://github.com/SharePoint/sp-dev-docs/issues/10074#issuecomment-2594248914 .  We pushed a configuration change to turn off this fix, and Natalie's working on redoing this fix so that it doesn't also break that scenario.

**Comment by Haiqi-Wu** [comment]
@reedpamsft When will the new fix roll out?

**Comment by vlad-nvs** [comment]
Hi.

This issue is still reproducible at the end of March 2025!
Any news about a fix?

**Comment by natalieethell** [comment]
Thanks for your patience here, sorry for the delay! We had two attempted fixes for this grouped view bug, but had to roll back because it seemed to cause some other issues. I'm looking into a new fix and will post updates here.

**Comment by PKOITC** [comment]
We have the same problem. Can we reopen the issue if it's not fixed ? Are there any know work-arounds ?

**Comment by wuxiaojun514** [comment]
@PKOITC I reopened it. Currently my work around is to avoid using group by in the view.

**Comment by natalieethell** [comment]
There was a change rolled out recently that should fix this issue. @RoelVB @wuxiaojun514 can you confirm?

**Comment by wuxiaojun514** [comment]
Hi @natalieethell 
It looks fine now, thanks for the hotfix, I will close it
