### ISSUE TITLE
API Permissions disappear from SharePoint admin center after approval

### ISSUE THREAD

**Issue by thomaskjaerulff** [SharePoint/sp-dev-docs#10041]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

I have a SPFx web part installed on a sharepoint enviroment with two Microsoft Graph webApiPermissionRequests in the package-solution.json file. 

Once the SPFx web part is deployed, I go to the Sharepoint Admin Site API Access Page to approve the Web Api Permission Requests. After approving them, it looks well, but when I refresh the page, or navigate away and back, I can`t see the approved items anymore.

After redeploying the SPFx package to the app catalog site, the previously approved Web Api Permission Requests are shown in the Pending Request section again.

We are seeing this issue on multiple tenants so we believe we are dealing with a general issue. 

### Steps to reproduce

1. Navigate to the https://tenant-admin.sharepoint.com/_layouts/15/online/AdminHome.aspx#/webApiPermissionManagement
2. Click on a pending request and approve it
3. Notice that the request has been visually approved and moved to the "Approved requests" group
4. Refresh the page and can not see the approved apis anymore
5. Upload the spfx package to the catalog site again
6. Refresh the WebAPIPermissionManagement Page again
7. The Approved API Items are shown in the Pending Request section

### Expected behavior

I expect that after approving the Web Api Permission Requests, they will remain in the Approved section on the Sharepoint Admin Site API Access Page.

**Comment by joelfmrodrigues** [comment]
Same here!

**Comment by thomaskjaerulff** [comment]
Thank you for your comment @joelfmrodrigues. You are absolutely right that this is a duplicate of [#9962](https://github.com/SharePoint/sp-dev-docs/issues/9962). 
Please keep me posted if you know anything about this issue. We currently have two Premier Microsoft Support cases open on this issue on two different tenants. We see this issue on every tenant we come across, so we are dealing with a general issue that has to be fixed.

**Comment by joelfmrodrigues** [comment]
@thomaskjaerulff I was able to grant permissions for platform APIs by granting them directly to the relevant Entra ID app registration that is used by SPFx. You can use this blog post from the awesome @michaelmaillot as an example: https://michaelmaillot.github.io/tips/20210302-spfx-api-permissions/
Unfortunately, for my own app this doesn't seem to work at the moment as I can't see it listed under "My APIs" tab, even though I can see the network request retriving it. Perhaps a separate bug on the Azure portal.

**Comment by thomaskjaerulff** [comment]
Thank you for the information @joelfmrodrigues. 
We did see this blog post and we have tried the suggested solution, however this was not working for us. 
When approving the Microsoft Graph permissions using this method, our custom API was lost and vice versa. 
If you have any other suggestions, kindly let me know.

**Comment by thomaskjaerulff** [comment]
For further information, when trying to use the m365 CLI as suggested by @michaelmaillot in his great blog post, I receive the error message: 

![image](https://github.com/user-attachments/assets/c49ef24a-9801-41f1-a220-00aa5fc5aeda)

**Comment by joelfmrodrigues** [comment]
@thomaskjaerulff I had the exact same issue trying to approve my custom API, very frustrating.
I also tried via m365 CLI and PnP.PowerShell, but no luck. At this point, I decided to hold on until there is a reply from MS on the issue as I am not sure if there is something else I can try

**Comment by thomaskjaerulff** [comment]
@joelfmrodrigues - Keep in mind that this is happening for a standard Microsoft Graph permission also. I will let you know if something comes out of the two Premier Microsoft Support cases I have running.

**Comment by joelfmrodrigues** [comment]
@thomaskjaerulff there is an update on the duplicated issue :)
https://github.com/SharePoint/sp-dev-docs/issues/9962

**Comment by thomaskjaerulff** [comment]
@joelfmrodrigues  - Yes, I got a similar response on the two Premier Microsoft Support cases I have open on two different tenants. However they said the fix will be rolled out the 20th. 
Having said the above, it is great that the issue will be resolved in the near future.

**Comment by VesaJuvonen** [comment]
As shared in the #9962, fix should be now out, but we would love to get this confirmed before closing this and the duplicate issue. Thanks for the confirmation advance 🙏

**Comment by thomaskjaerulff** [comment]
Thank you for joining the conversation @VesaJuvonen. 
I just tested approving Microsoft Graph permissions, and unfortunately the issue still remains. 
Immediately after approving the permissions, it looks correct, but when navigating away and back or refreshing the API access page, the permissions disappear.

**Comment by joelfmrodrigues** [comment]
The same behaviour here. Approving seems to work and I see no errors on the console network requests, but then refresh the page and the approved permission is gone. Trying to approve via M365 CLI or PnP.PowerShell also still doesn't work.

**Comment by thomaskjaerulff** [comment]
@VesaJuvonen & @joelfmrodrigues - My assumption is, that there is something wrong with the app registration "SharePoint Online Client Extensibility Web Application Principal"

![image](https://github.com/user-attachments/assets/c8e9faca-905a-4005-9aba-6f32e78ac3a3)

**Comment by thomaskjaerulff** [comment]
@VesaJuvonen - I've received e-mails from the two Microsoft Premier Support cases (created on separate tenants), that the issue has been fixed. However after checking, the issue unfortunately still remains. Do you have any update?

**Comment by thomaskjaerulff** [comment]
@joelfmrodrigues - Is the issue the same on your tenant(s)?

**Comment by joelfmrodrigues** [comment]
@thomaskjaerulff  yes exactly the same error, and I confirm that it is still not fixed

**Comment by thomaskjaerulff** [comment]
@joelfmrodrigues and @VesaJuvonen - I tried on the existing environments again this morning. Here the issue still remains. 
I then created a brand new demo environment, and here I was able to approve the Microsoft Graph permissions without any issues. Please see screenshot below: 

![image](https://github.com/user-attachments/assets/3b8b6798-e2dd-4d63-8f22-87cfcc5bf148)

I'm worried about the existing environments. Do I need to do something actively to get it to work on these environments?

**Comment by joelfmrodrigues** [comment]
Quick update to this. I tried to get the SharePoint Online Client Extensibility Web Application Principal app registration recreated in hope of having the issue resolved, but still no luck.

1. Deleted the app registration and waited a moment for the associated enterprise application to also be automatically deleted.
2. Visited the API access page within the M365 admin portal as I knew from past issues that this would trigger the creation of a new SharePoint Online Client Extensibility Web Application Principal app
3. Checked the network tab in dev tools and could see all requests going on to provision the new app without issues
4. Confirmed that the new app was created and expected default app configurations seemed to be in place
5. Tried to approve permissions again, but same issue 😫

**Comment by joelfmrodrigues** [comment]
@thomaskjaerulff Unfortunately I am in the same place as before :( Deploying our solution to a separate client tenant and crossing my fingers I don't find the same issues there as it would be a huge problem

**Comment by thomaskjaerulff** [comment]
@joelfmrodrigues I found that it was working fine on newly created demo tenants. But not on existing tenants. This is a big problem for us.

**Comment by joelfmrodrigues** [comment]
@thomaskjaerulff I just noticed that on my tenant I have the app `SharePoint Online Client Extensibility Web Application Principal`, but the app `SharePoint Online Client Extensibility Web Application Principal Helper` is missing. Can you please confirm if the "Helper" app is also missing on your side?

**Comment by thomaskjaerulff** [comment]
@joelfmrodrigues I have both app registrations. The `SharePoint Online Client Extensibility Web Application Principal` and the `SharePoint Online Client Extensibility Web Application Principal Helper`. 
Found this interesting post: https://ericschrader.wordpress.com/2020/06/23/sharepoint-online-bad-service-principal-breaks-sharepoint-admin-api-access-global-service-principal-id-error-resolved/

**Comment by joelfmrodrigues** [comment]
@thomaskjaerulff that doesn't seem to apply to me as I only have one app registration 😇 and the ID matches the ID in the page source code

**Comment by joelfmrodrigues** [comment]
And now I found this also on the client's prod tenant 😟

**Comment by joelfmrodrigues** [comment]
@thomaskjaerulff  it just started working on the two tenants I found the issue!

**Comment by thomaskjaerulff** [comment]
@joelfmrodrigues good to hear. I'm glad you got it working. I just tested on one of our customer tenants, and here the issue is still the same unfortunenately. Maybe it just takes time to roll out the fix. At least, that is what I hope. Maybe you can confirm this @VesaJuvonen ?

**Comment by thomaskjaerulff** [comment]
@joelfmrodrigues & @VesaJuvonen here is a recording made this morning of my experience: https://fellowminddk-my.sharepoint.com/:v:/g/personal/thomas_kjaerulff_fellowmind_dk/ESu6Mjw6HKxGm_RWix6uwwsBtYEVxIFao_cIe2-fjeenbw?e=5djdgi

**Comment by thomaskjaerulff** [comment]
@joelfmrodrigues & @VesaJuvonen 
Running a network trace when approving the permissions shows me that the approval flow is looking for an application id that does not exist on the tenant. The app registration exists, but with a different ID. This is the case for both tenants where we are running Microsoft Premier Support cases. 
Also, we see a "Deny" call which does not have any response data available. 

![image](https://github.com/user-attachments/assets/7881c94f-e1e7-4e94-b7a1-75e42246a011)

We are really desparate to find a solution here :(

**Comment by lucabandMSFT** [comment]
@thomaskjaerulff , that seems unlikely. That app exists to all tenants. you can look at it from the "Enterprise Application" option in the Azure Portal. Can you please search for "SharePoint Online Web Client Extensibility" and confirm that the APP ID is indeed that one? Also, can you confirm that the application is enabled (in Azure)?

**Comment by thomaskjaerulff** [comment]
@lucabandMSFT (CC: @joelfmrodrigues & @VesaJuvonen)- Thank you for your feedback. The app "SharePoint Online Web Client Extensibility" is located in the "App Registration" section in Azure. Not in the "Enterprise Application" area.

![image](https://github.com/user-attachments/assets/ce00a154-16cb-4dc4-81e6-d57615ca0d11)

How do I confirm that the app is enabled in Azure? 
If I run the cmdlet "Enable-SPOTenantServicePrincipal", I receive "Unknown error": 

![image](https://github.com/user-attachments/assets/32c1930f-576f-4893-b703-7cda8095d62a)

**Comment by joelfmrodrigues** [comment]
@thomaskjaerulff there should be another app with the same name under Enterprise Applications. You should be able to open the one that you have on your screen and at the top of the details screen there should be a link to the relevant enterprise application

**Comment by thomaskjaerulff** [comment]
@joelfmrodrigues & @lucabandMSFT I see the Enterprise Application now. 
Is there anything specific I should check here? This issue still remains, so I would be SO happy if you could direct me in what to check. 

![image](https://github.com/user-attachments/assets/9925cf29-5404-4c83-91d5-6dde8a3fbde0)

**Comment by thomaskjaerulff** [comment]
@joelfmrodrigues - If you are keen on it, I would love to get in touch with you over a Teams call to connect and discuss this matter and findings. If at all possible, I would like to get your view on this. I would love to connect. 
You can reach me at thomas.kjaerulff **[at-sign]** fellowmind.dk

**Comment by joelfmrodrigues** [comment]
Hi Thomas, happy to discuss via LinkedIn. Not sure if I can be of much help, but happy to have a call to discuss.

**Comment by Tanddant** [comment]
We're also seeing this issue on a client tenant now - seems to have "reappeared"

**Comment by marcus-atvero** [comment]
We're also seeing this on multiple client tenants as well.

**Comment by thomaskjaerulff** [comment]
@Tanddant thank you for your feedback. Has the issue been there before?

**Comment by Tanddant** [comment]
> @Tanddant thank you for your feedback. Has the issue been there before? 

We did observe this issue on a different tenant last summer, but just skipped the approval page, and added the permissions straight to the app registration 

(Re our recent call @VesaJuvonen)

**Comment by Tanddant** [comment]
Interesting update - the permissions have appeared, and things seem to be working, feels like it took right around 24 hours from being approved to appearing 🤔

**Comment by marcus-atvero** [comment]
@thomaskjaerulff we are currently working around it by applying the permissions manually to the SPFx Helper App Registration (Not the Enterprise App registration).  It's a painful manual process but gets our customers working again.  It's important to add the API permissions, then consent to them.  I did notice that the first time you add the permissions manually and then press Grant Admin Consent for <tenant> it prompts about if you want to add them to the existing, or delete existing ones.  That doesn't then actually grant consent, you have to consent a second time, then the permissions appear in the SharePoint API.

We've not had a problem with keeping both the custom app and the Graph ones as we go through this process.

We've seen numerous issues in the last couple of months - missing default client IDs built in, Sharepoint API manager unable to automatically rebuild the SPFx Helper if you delete it (like it should be able to), the client secrets in the SPFX helper looking garbled, uploading SPFx and it approving the Graph permissions but not our custom app registrations, and now approving the custom app registration permissions but not Graph permissions.  It's made our software look pretty poor to new customers as we've failed to install.

**Comment by GrahamMcMynn** [comment]
The bug was identified which caused the issue with permissions disappearing.  However, we couldn't roll back to fix the issue.  A fix has been made and should be in production by January 27th.

**Comment by Tanddant** [comment]
@GrahamMcMynn will any permissions attempted approved in the meantime be granted correctly, or roll back as a requested permissions, so we can approve them again?

**Comment by Ashlesha-MSFT** [comment]
@thomaskjaerulff , @GrahamMcMynn,
If the behavior has been resolved and the approved permissions now remain visible, could we go ahead and close this issue?
