### ISSUE TITLE
People Search REST API 401 Response

### ISSUE THREAD

**Issue by kristen-argent** [SharePoint/sp-dev-docs#10246]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

SharePoint REST API

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [x] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

Hitting the API in any way 

### Describe the bug / error

We have developed an application that makes use of the rest search API - until Tuesday this was working well in all environments.

Since then it has ceased working in some environments (Australian) and is now returning a 401 Unauthorized response.
It continues to work in two of our tenants (US based)

We use sourceId=B09A7990-05EA-4AF9-81EF-EDFAB16C4E31.

The query is being run by the application entra id, not using a user token.
Hitting search api without the source id filter also works correctly.

### Steps to reproduce

Request URL with app token.

https://___.sharepoint.com/_api/search/query?querytext=%27user%27&sourceid=%27b09a7990-05ea-4af9-81ef-edfab16c4e31%i27

### Expected behavior

Search results returned

**Comment by Ashlesha-MSFT** [comment]
Hello @kristen-argent,
Thank you for bringing this issue to our attention. We will look into it and get back to you shortly.

**Comment by Ashlesha-MSFT** [comment]
@kristen-argent,

We were unable to reproduce the issue in our tenant. To assist further, could you please share the tenant details? This will help us escalate and investigate the matter more effectively with our engineering team.

![Image](https://github.com/user-attachments/assets/b44020f4-f138-4458-b1c7-ddbd28528208)

**Comment by kristen-argent** [comment]
@Ashlesha-MSFT 

The tenant with issues:

![Image](https://github.com/user-attachments/assets/0051ef48-af5c-410e-9ad4-76c4738f9d19)

The tenant still working:

![Image](https://github.com/user-attachments/assets/d9905b1d-fffa-4138-a910-6b37e9f432a2)

**Comment by kristen-argent** [comment]
@Ashlesha-MSFT any update on this issue? Looks like you have been able to reproduce after the tenant information was provided? Are we likely to see a fix soon?

**Comment by Ashlesha-MSFT** [comment]
@kristen-argent,
We’ve logged this issue as a bug already, and our engineering team is currently investigating it.
They’re working on a fix and it should be addressed soon.

**Comment by MortenPedersenDK** [comment]
Not sure if it is related, but in some tenants I get 401 Unauthorized when calling the Search REST API like below, while in other tenants I do not.

```
https://tenant.sharepoint.com/sites/intranet/_api/search/query?querytext=%27DepartmentId:98459155-b50b-431b-968c-b6d9aedeeb65%20contentclass:STS_Site%27&selectproperties=%27Path,ContentClass,SiteId%27
```
I have checked the App registration in entra, and they are 100% identical.

I use HttpClient for the call, using Bearer token like this:

```
var url = baseUrl + $"/_api/search/query?querytext=%27DepartmentId:{hubId.ToString()}%20contentclass:STS_Site%27&selectproperties=%27Path,ContentClass,SiteId%27";
var req = new HttpRequestMessage(HttpMethod.Get, url);
var token = ctx.GetAccessToken();
req.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
HttpClient http = new HttpClient();
http.DefaultRequestHeaders.Accept.Clear();
http.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

var response = await http.SendAsync(req);
string json = await response.Content.ReadAsStringAsync();

```
On the failing tenants I get this response:

```
{"odata.error":{"code":"-1, Microsoft.Office.Server.Search.REST.SearchServiceException","message":{"lang":"da-DK","value":"Uautoriseret."}}}
```

**Comment by VesaJuvonen** [comment]
This was an issue on the Microsoft yesterday, which was also logged at the tenant status updates. Issue has been resolved. You can find a b it more details on the following GitHub issue  where this was also discussed in the context of PnP search web parts - https://github.com/microsoft-search/pnp-modern-search/issues/4361.

Closing as resolved.

**Comment by kristen-argent** [comment]
@VesaJuvonen with all due respect this issue was completely different from the issue yesterday and is still occurring. I would like this issue re opened as I believe there is a fix being developed as per @Ashlesha-MSFT.
If it’s not reopened I’ll be raising another bug shortly.

**Comment by SaschaHenning** [comment]
Hi - same here... Error still occurs.

We have an app which has all necessary access. The Submit-PnPSearchQuery for the SourceId "b09a7990-05ea-4af9-81ef-edfab16c4e31" (People) returns an access error. It works fine with other Sources (or without a SourceId using the default one)

![Image](https://github.com/user-attachments/assets/4bfd1525-8bb5-44bc-88cb-5d51832772c1)

This stopped working last week.

**Comment by MortenPedersenDK** [comment]
Still unsure whether related, but @VesaJuvonen I still get same error as mentioned above.

**Comment by kristen-argent** [comment]
Will comment on both these tickets but all of our tenants are now impacted by this issue.

**Comment by SReid01** [comment]
have exact same issue. I also have a ticket in as well.

**Comment by f0oster** [comment]
As per my note in #10261 - also still experiencing the sane issues querying SourceId b09a7990-05ea-4af9-81ef-edfab16c4e31.

@VesaJuvonen I think this should be reopened?

**Comment by VesaJuvonen** [comment]
Reopening based on comments. Hopefully gets also routed with other channels to the support pipeline.

**Comment by Ashlesha-MSFT** [comment]
@f0oster, @SaschaHenning, @kristen-argent Please verify if everything is resolved on your end and, if so, proceed to close the issue.

**Comment by f0oster** [comment]
Confirming that the issues were resolved for me as per #10261

**Comment by Ashlesha-MSFT** [comment]
Thanks everyone for your patience and collaboration throughout this issue.

As the functionality has been restored and no further reports of failure have come in, we’ll go ahead and close this issue
