### ISSUE TITLE
BUG: Webparts isn't respecting the manifest group default title location in classic page

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/sp-dev-docs#1024]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

All of my webparts all the sudden no longer located in the correct classic webpart folder. This happens on cross tenants.
Configuration:
![image](https://user-images.githubusercontent.com/6864547/32420986-5dadf62e-c2e7-11e7-94a1-8d84e237eeec.png)

Result:
![image](https://user-images.githubusercontent.com/6864547/32421022-c1bbfe36-c2e7-11e7-8fff-8d3cb064cfed.png)

Expected result is the webpart should be within the "Sample Group" folder instead of the "Other" folder.

**Comment by matthong** [comment]
We are having the same issue.

**Comment by manishgarg1** [comment]
Hi @jonathanhotono, @matthong , thanx for reporting the issue. We believe the issue should now be fixed. Please close the bug if that is true.

**Comment by jonathanhotono** [comment]
@manishgarg1 I am still seeing all my webparts within "Other" folder across tenants.

**Comment by matthong** [comment]
We are still seeing our Web Parts in the Other folder too.

**Comment by manishgarg1** [comment]
Hi, sorry for the delay. Can folks confirm if this is resolved now?

**Comment by matthong** [comment]
Confirm that the issue has been resolved in my tenants. Thanks!

**Comment by manishgarg1** [comment]
Resolving since the issue is confirmed resolved
