### ISSUE TITLE
"The package contains the wrong number of relationships for relationship type 'http://schemas.microsoft.com/sharepoint/2012/app/relationships/package-manifest'. Expected: '1'. Actual: '0'."

### ISSUE THREAD

**Issue by PChinari** [SharePoint/sp-dev-docs#10481]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [x] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

When I try to upload the package in sharepoint manage apps I get the error saying" "The package contains the wrong number of relationships for relationship type 'http://schemas.microsoft.com/sharepoint/2012/app/relationships/package-manifest'. Expected: '1'. Actual: '0'." .

### Steps to reproduce

1.
2.
3.

### Expected behavior

It should upload the package successfully in sharepoint.

**Comment by Ashlesha-MSFT** [comment]
Hello @PChinari,
Thank you for bringing this issue to our attention. We will look into it and get back to you shortly.  
If you don’t receive a reply within two working days, please use this [escalation form](https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR4mTPG34N0xHuJATbbeqmGlUNlAwSlpSNlpPTkszVkRPMFgzNVdaS0dTUy4u) to escalate.

**Comment by Ashlesha-MSFT** [comment]
@PChinari,
From the error message and the package contents, it appears that the file may have been modified outside of the standard SPFx build process. In several cases we’ve seen, the issue occurs when the .sppkg file is manually zipped, or when both a .zip and .sppkg version of the package exist and the wrong one is uploaded. Although an .sppkg is technically a ZIP format, modifying or re-archiving it externally can remove required relationships—such as the package-manifest reference—leading to the “Expected: ‘1’, Actual: ‘0’” error.

Could you please try reproducing this using a clean, unmodified .sppkg generated directly from your SPFx solution (without re-zipping or packaging it manually)? This will help confirm whether the package was altered somewhere in the process.

You may also find this related issue helpful: https://github.com/SharePoint/sp-dev-docs/issues/7450

Let us know what you find, and we’ll be happy to assist further.

**Comment by Ashlesha-MSFT** [comment]
@PChinari,
Just checking in to see if you had a chance to try uploading a clean, unmodified .sppkg file as suggested above. Were you able to resolve the issue?

If the problem is now fixed, please let us know so we can go ahead and close this issue.

**Comment by PChinari** [comment]
Thank you for checking out Ashleya but when I upload it did work but I need
to change content in json file and upload so uploading it’s taking as
different file I guess … so problem is not fixed yet …can you please share
information on how to make the package from scratch and then upload .

**Comment by Ashlesha-MSFT** [comment]
@PChinari,

- Clean, Build, Bundle, and Package the Solution

Execute the following commands in your SPFx project root:
```
gulp clean
gulp build
gulp bundle --ship
gulp package-solution --ship
```

- Use the Generated .sppkg Directly

After running the above commands, your package will be generated in:
`sharepoint/solution/<your-solution>.sppkg.`
Do not open it, change it, or zip it again. Just take the file that was created and upload it. Changing it can break it and cause the error again.
For more details on packaging and deploying SPFx solutions, please refer to the official Microsoft guide:
[Serve your web part in a SharePoint page](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page)

Hope this helps!

**Comment by PChinari** [comment]
Thank you Ashlesha I will try and update you on my results .

**Comment by Ashlesha-MSFT** [comment]
@PChinari,
Just checking in to see if you had a chance to try the clean rebuild and packaging steps after updating your JSON file. Could you please share an update on whether this resolved the issue?
Thank you!

**Comment by Ashlesha-MSFT** [comment]
@PChinari,
Could you please share an update on whether this resolved the issue?
Thank you!

**Comment by Ashlesha-MSFT** [comment]
@PChinari,
Any update?

**Comment by Ashlesha-MSFT** [comment]
We haven’t received any further updates from the author despite multiple follow-ups and guidance provided on rebuilding and packaging the SPFx solution correctly. Since there’s no additional information to proceed and the recommended steps were shared, we’re closing this issue due to inactivity.

If the problem persists after following the clean build and packaging steps, please feel free to open a new issue with updated details.
