### ISSUE TITLE
[SPFx 1.22.1] Allow debug scripts pop up appears every time the page refreshes after making a change.

### ISSUE THREAD

**Issue by kbeverforden** [SharePoint/sp-dev-docs#10529]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [x] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

If you create a brand new 1.22.1 project (possibly 1.22.0, as well) and edit the default web part and click save it will automatically refresh the page but show this pop up again. If you click "Load debug scripts" it will refresh the page with your changes applied. I can also replicate this on an existing project that I upgraded to 1.22.1.

<img width="1265" height="278" alt="Image" src="https://github.com/user-attachments/assets/04d3dcab-5bb7-4fb8-a4cc-18364666dccb" />

### Steps to reproduce

See message above

### Expected behavior

This pop up used to only appear once but now it's appearing on every save.

**Comment by Ashlesha-MSFT** [comment]
Hello @kbeverforden,
Thank you for bringing this issue to our attention. We will look into it and get back to you shortly.  
If you don’t receive a reply within two working days, please use this [escalation form](https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR4mTPG34N0xHuJATbbeqmGlUNlAwSlpSNlpPTkszVkRPMFgzNVdaS0dTUy4u) to escalate.

**Comment by Tanddant** [comment]
@kbeverforden - Could you share some more info about your configuration? - I'm not seeing this 🤔 AFAIK it's not directly related to SPFx, it's just on the SharePoint side of things, so would be interesting if this is a browser issue, are you blocking cookies, or something? - different browser, inPrivate, ect. is this something you're seeing everywhere?

**Comment by Ashlesha-MSFT** [comment]
@kbeverforden,
We were able to reproduce this issue in our tenant using SPFx 1.22.1. The “Allow debug scripts” prompt now appears on every page refresh after saving changes (Even if you won't update the files just refresh "Load debug scripts" appears), whereas previously it only appeared once per session.

We have logged this behavior as a bug, and our engineering team is actively investigating the root cause.
Thanks for reporting this and for your patience.

**Comment by Ashlesha-MSFT** [comment]
Hi @kbeverforden,

We've tested this on our end using SPFx 1.22.1 and the "Allow debug scripts" popup is no longer appearing on every page refresh after saving changes. It seems this may have been resolved.

Could you please verify on your end as well? If you're also not seeing the issue anymore, we can go ahead and close this.

Thanks!

**Comment by kbeverforden** [comment]
@Ashlesha-MSFT The pop up still appears every refresh using the workbench. I saw that the workbench is being deprecated in the v1.23 release notes. I tried it the new way using this at the end of the site URL

`?loadSPFX=true&debugManifestsFile=https%3A%2F%2Flocalhost%3A4321%2Ftemp%2Fbuild%2Fmanifests.js`

and the pop up does NOT appear every reload. Since the workbench is going away I think I can close this ticket as obsolete.
