### ISSUE TITLE
Error occurred in deployment step 'Install SharePoint Add-in': The remote server returned an error: (429).

### ISSUE THREAD

**Issue by bmanning31** [SharePoint/sp-dev-docs#1384]
- [ ] Question
- [ ] Typo
- [ X] Bug
- [ ] Additional article idea

I'm trying to deploy a custom add-in to a sharepoint online developer site.  I've been getting this error ever since issue #1318.  I found that doing a separate retraction before deploy helps, but I get this error both on retract and deploy.  yesterday, i had no problems.  Today, I can't do anything without getting this error.  

> ------ Build started: Project: pbi_dev, Configuration: Debug Any CPU ------
> ------ Deploy started: Project: pbi_dev, Configuration: Debug Any CPU ------
> Active Deployment Configuration: Deploy SharePoint Add-in
>   Skipping deployment step because a pre-deployment command is not specified.
>   Skipping the uninstall step because the SharePoint Add-in is not installed on the server.
>   Install SharePoint Add-in:
>   Uploading the SharePoint Add-in...
>   Installation is in progress (00:00:00)
>   Installation is in progress (00:00:02)
>   Installation is in progress (00:00:04)
>   Installation is in progress (00:00:06)
>   Installation is in progress (00:00:08)
>   Installation is in progress (00:00:09)
>   Installation is in progress (00:00:12)
>   Installation is in progress (00:00:13)
>   Installation is in progress (00:00:15)
>   Installation is in progress (00:00:17)
>   Installation is in progress (00:00:18)
>   Installation is in progress (00:00:20)
>   Installation is in progress (00:00:22)
>   Installation is in progress (00:00:24)
>   Installation is in progress (00:00:26)
>   Installation is in progress (00:00:27)
>   Installation is in progress (00:00:29)
>   Installation is in progress (00:00:31)
>   Installation is in progress (00:00:33)
>   Installation is in progress (00:00:35)
>   Installation is in progress (00:00:37)
>   Installation is in progress (00:00:38)
>   Installation is in progress (00:00:40)
>   Installation is in progress (00:00:42)
>   Installation is in progress (00:00:44)
>   Installation is in progress (00:00:46)
> Error occurred in deployment step 'Install SharePoint Add-in': The remote server returned an error: (429).
> ========== Build: 1 succeeded or up-to-date, 0 failed, 0 skipped ==========
> ========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========

Thanks in advance

P.S.

I also still get the same errors as during the #1318 issue.  Just got this one 30 seconds ago.

> ------ Build started: Project: pbi_dev, Configuration: Debug Any CPU ------
> ------ Deploy started: Project: pbi_dev, Configuration: Debug Any CPU ------
> Active Deployment Configuration: Deploy SharePoint Add-in
>   Skipping deployment step because a pre-deployment command is not specified.
>   Skipping the uninstall step because the SharePoint Add-in is in an invalid state and cannot be uninstalled.
>   Install SharePoint Add-in:
>   Uploading the SharePoint Add-in...
> Error occurred in deployment step 'Install SharePoint Add-in': An instance of this App already exists at the specified location.
> ========== Build: 1 succeeded or up-to-date, 0 failed, 0 skipped ==========
> ========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by bmanning31** [comment]
Anyone?  does anyone have a work around I could try?  I'm dead in the water with this problem.

**Comment by nickpape-msft** [comment]
@mcmynn83

**Comment by VesaJuvonen** [comment]
@bmanning31 - we are looking into this internally. Most likely this issue is already resolved on your tenant, but if not, please let us know.

**Comment by phoegfeldt** [comment]
I still have the same problem. For 2,5 weeks now. I created a support ticket. A Microsoft engineer ran a 4 hours diagnostic on my SharePoint server yesterday. Unfortunately this didn't solve the problem. So it has now been escalated with Microsoft support.

**Comment by VesaJuvonen** [comment]
Hi @bmanning31, @phoegfeldt  - We would need to have slightly more details on this as there's no way to understand what goes wrong without correlation ID and time - so that our throttling people can have a look on the logs what actually happened. If either one of you has the exact time and correlation ID to share, that would get the issue resolution forward... if you can re-initiate the action and that results in a correlation ID - that would be optimal.

**Comment by VesaJuvonen** [comment]
Also if the issue is still present, we can have a closer look on it from the logs side, we would just need to know the URL of the site and the app, which is in the failed state.

**Comment by lucaband** [comment]
Since we have not heard about this issue from more than two weeks, we are going to close this issue for now.
Please open an new issue with logs and correlation ID so we can do further proper investigation.
