### ISSUE TITLE
MSGraphClient - Refresh Access Token in SharePoint Framework WebPart

### ISSUE THREAD

**Issue by aslanovsergey** [SharePoint/sp-dev-docs#1420]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
How I can refresh MS Graph Access token in my App? In case it's opened for a while it throws "Access token has expired".
I initialize graphClient right at the moment of invocation
```
        const graphClient: MSGraphClient = this.props.context.serviceScope.consume(
            MSGraphClient.serviceKey
          );
```

**Comment by aslanovsergey** [comment]
I get the following error after a page with webpart has been opening for a while
```
Error: Token renewal operation failed due to timeout
    at Array.<anonymous> (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-02-16.005/sp-webpart-workbench-assembly_en-us_1a6be7933ec03c168be3b14c1835ecd8.js:743:31336)
    at Object._callBackMappedToRenewStates.(anonymous function)._callBackMappedToRenewStates.(anonymous function) (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-02-16.005/0.sp-http-adal_4a41848c866052caa755.js:3:7561)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-02-16.005/0.sp-http-adal_4a41848c866052caa755.js:3:10035
```

**Comment by patmill** [comment]
Hi @aslanovsergey - thanks for the report.  It should be fixed in a drop in the near future.

**Comment by lucaband** [comment]
Thank you very much. 
At this point the issue is solved and the fix is in production for all tenants. if that is not the case please open a new issue with information on where (which tenant) this issue occurs

**Comment by aslanovsergey** [comment]
Still get this error
Error: Token renewal operation failed due to timeout
    at Array.<anonymous> (sp-pages-assembly_en-us_06b01c8be14801565bc44fa27ac02d8a.js:939)
    at Object._callBackMappedToRenewStates.(/sites/spdev/SitePages/anonymous function)._callBackMappedToRenewStates.(anonymous function) (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-06-29.008/0.sp-http-adal_a4a92f585422c0345c73.js:3:7561)
    at 0.sp-http-adal_a4a92f585422c0345c73.js:3
