### ISSUE TITLE
All calls with MSGraphClient return 403

### ISSUE THREAD

**Issue by Nasicus** [SharePoint/sp-dev-docs#1946]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

SPFx 1.4.1.

Using the `MSGraphClient` gives a  `403` exception since a few days:

```
Error: 403: Access is denied. Check credentials and try again.
```

In the manifest we still have the same permissions as before.
We also didn't change any code at all!

See also: https://github.com/SharePoint/sp-dev-docs/issues/1934#issuecomment-394306890

**Comment by waldekmastykarz** [comment]
The permissions listed in the manifest are used only to provision a permission request that needs to be approved by the tenant admin. It doesn't mean that these permissions are automatically granted. If the tenant admin revoked previously granted permissions, your code could indeed stop working without any changes to it.

To verify the permissions you have to access the Microsoft Graph either:
- see the contents of the JWT token used when calling the MS Graph API using a tool like jwt.io, or
- see the API management page in the SharePoint tenant admin site

**Comment by justdevelopment** [comment]
This issue started yesterday morning without any changes to code or permissions granted. We have the same thing on 4 different tenants, all with calls from MSGraphClient. I've tried re-authorizing the addin (full reinstall including all permissions re-approved) but no luck. It's a breaking issue, we can not continue development right now... If there is a change in code we'd love to know so we can update and continue our project.

**Comment by Nasicus** [comment]
@waldekmastykarz  same as @justdevelopment  said.... we are also blocked.

**Comment by waldekmastykarz** [comment]
Have you verified your access token and if the granted permissions match the permissions required by the particular MS Graph API you're calling?

**Comment by MatthiasWeibel** [comment]
As the others already said: there was no change to anything: no change to the permissions granted, no change to the permissions required, no change to the code, no change to MS Graph API called.
Code and granted permissions that were working together last week stopped working without any changes.

**Comment by justdevelopment** [comment]
Seems like whatever is happening behind the scenes is not requesting the proper permission scopes or something similar. 
When I check the token for authorization (using http://jwt.calebb.net/) it's not as we request. The only scope in there is "People.Read user_impersonation", we definitely have a lot more in our manifest, CA etc. This code was working 100% last week, no changes made by us.

**Comment by weshackett** [comment]
We're also seeing this behaviour with a set of SPFx code which is unchanged. Checking the token from SPFx it is only returning the basic login scope. We've tried across several tenants and even removed and retrusted the API in the Tenant Admin UX. All with no changes to this behaviour. Seems to have only been happening since Monday morning (4/6/2018)

**Comment by JHolah** [comment]
I am seeing this exact same issue. No code change, no permissions revocation. All requests to the graph now return 403.

The only additional thing I have seen is, as others have noted, that the token issued only contains the scope "People.Read user_impersonation" which suggests that the scopes added via the manifest are no longer being respected and only the default scope is enabled.

**Comment by VesaJuvonen** [comment]
Thanks for reporting, we'll start an investigation right away. Have reported this forward as it seems to be an issue in the underlying platform. We'll get it sorted out asap, but it will take a while still as the capability is currently in preview, so there's no Support for it through official channels yet and the majority of the engineers are in the Pacific areas.

**Comment by yonas101** [comment]
Same thing for me,  SPFx Extension that worked friday and this week it suddenly stopped working,  returning 403 while trying to access Mail.ReadWrite scope.
tried reinstalling and reauthenticating the apirequest in tenantadmin but no luck.

**Comment by Nasicus** [comment]
@VesaJuvonen 
I understand that it's still in preview, but since day one when SPFx 1.4.1 came out the documentation had this title & headline:

![image](https://user-images.githubusercontent.com/1086065/40972183-30cb61a8-68c0-11e8-9d9a-564daed207e6.png)

So from the beginning you could either decide to use the already marked as deprecated client or the new one (which was still in preview) - there is no real "in-between"/perfect solution here in my opinion....so the choice for every new project was pretty obvious for us ;)

I don't write this to blame you, just want to tell you "our side" so you can understand why most of us "expect" the new client to work :)

**Comment by VesaJuvonen** [comment]
Deprecation means that it's supported but we are not investing in that option anymore. It does not mean that it's not supported. We need to still fix certain things around MSGraphClient until we can ship that to be ready for production usage. We absolutely understand the inconvenience this will cause for our ISVs and customers so trying to solve the situation as fast as possible.

Now - in this case, we have not yet identified the root cause of what has happened. We definitely should not break you without any warning even though capability would be "only in preview".

**Comment by bastianjohn** [comment]
Same issue with MSGraphClient here, without updating anything it stopped working. Thanks for investigating the issue @VesaJuvonen

**Comment by patmill** [comment]
OK, sorted out the issue.  It should be fixed now, and it might take 1 hour for your tokens to expire and then work.  The problem had to do with someone removing the scopes associated with the app.  We are taking measures to ensure that can't happen in the future.

**Comment by Nasicus** [comment]
@patmill @VesaJuvonen 
Confirmed. It's working again - thanks for your commitment guys!

Btw: The other one was introduced around the same time frame, maybe a little later and is still not working: https://github.com/SharePoint/sp-dev-docs/issues/1934

(I will close as soon as some of the other guys give feedback :) )

**Comment by bastianjohn** [comment]
@patmill @VesaJuvonen
It is also working for me! Thanks for your quick fix!

**Comment by JHolah** [comment]
Confirm also working for me. Thank you for the quick fix.

**Comment by yonas101** [comment]
Thanxs for the quick fix, awesome work =)
