### ISSUE TITLE
1.5.0 Framework - FatalError: error TS5023: Unknown compiler option 'typescript'.

### ISSUE THREAD

**Issue by PooLP** [SharePoint/sp-dev-docs#2077]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

Hi,
With latest Visual Studio Code Insiders and a hellowold Webpart on 1.5.0 Frameworks, I have this warning, after second save (I have no error after first launch of Gulp task) : 

Warning - [tslint] Unable to create a TS program for TSLint. Some lint rules might not work correctly. Error FatalError: error TS5023: Unknown compiler option 'typescript'.

Do you also have this warning?

Thanks

**Comment by PooLP** [comment]
After more test on cmd (outside of VSC) i have same error on fresh initialisation of helloworld (application customizer)

I run this on a PC with Windows 10 (1803), 64bits, node 8.10.0 & npm 5.6.0

**Comment by GolaWaya** [comment]
This is actually a problem with the @microsoft/gulp-core-build-typescript which SharePoint framework uses to compile.  See https://github.com/Microsoft/web-build-tools/issues/712  I have included a fix in the issue.

**Comment by VesaJuvonen** [comment]
The issue has been fixed in the web-build-tools, so it should be now resolved. Sorry for the inconvenience.

**Comment by StfBauer** [comment]
@VesaJuvonen The issue still exists in 1.5.1.

**Comment by praveenbattula** [comment]
Yes, it still exists with latest spfx version. Will look for next beta version.
