### ISSUE TITLE
Modern Themes Broken - Multiple Tenants

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-docs#2434]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Modern Themes should load for the tenant.

#### Observed Behavior

When selecting Change the Look, it does not show all the themes for the tenant. It does in PowerShell. See attached image.

![broken theme](https://user-images.githubusercontent.com/8781041/44768287-c5467180-ab58-11e8-9188-b49510d041b8.jpg)
![themes in tenant](https://user-images.githubusercontent.com/8781041/44768290-c5467180-ab58-11e8-9928-cc56e8ae26c9.jpg)

This has been observed in 3 separate tenants in the UK.

#### Steps to Reproduce

- Create and add theme to tenant
- Create Communication Site
- Cog > Change the Look - Only 1 current theme is shown

Thanks for your contribution! Sharing is caring.

**Comment by nhadro** [comment]
I am having the same issue in all of my tenants.

**Comment by bethleota** [comment]
I've seen this same issue in 3 different tenants.

**Comment by thechriskent** [comment]
Currently, this still works in my tenant on list view pages, but otherwise Nope.

**Comment by bethleota** [comment]
Thanks @pkbullock I am able to change the theme from Site Contents area now. Seems really strange that's where one has to go to do that.

**Comment by pkbullock** [comment]
Credit goes to @thechriskent for his suggestion. @bethleota its not normally like that, just a workaround for now. I was using this feature heavily yesterday without any issues, this is likely to be a bug.

**Comment by bethleota** [comment]
Thanks @thechriskent!!! Yes, @nhadro  and I were going a little bonkers yesterday when we noticed 'change the look' kept taking us to classic themes. Glad there is a workaround for now and hope this bug will be fixed soon.

**Comment by RichBurdes1** [comment]
@thechriskent - great work around! kudos goes to you - got me out of a jam presenting about themes!

**Comment by VesaJuvonen** [comment]
Sorry for the delay on this. This was a regression which was fixed pretty soon when it happened. Thanks, everyone for participating in the discussion for this. Closing as it's now fixed.

**Comment by Promhize** [comment]
This issue is back and is fairly easy to reproduce.

Steps
1. Use the REST API to create and apply theme
2. Reload any modern page including the site contents
3. Open **change the look**.

Result
**Change the look** is empty
![image 2018-12-05 at 10 31 05 am](https://user-images.githubusercontent.com/20524675/49503992-0a292500-f879-11e8-99e9-8df4b06de7e0.png)


And there's a network error for this endpoint: `/sites/ShortPoint/_api/SP.Web.GetContextWebThemeData?noImages=true&lcid=en%2DUS`
Error code: **500**
![image 2018-12-05 at 10 33 38 am](https://user-images.githubusercontent.com/20524675/49504177-73a93380-f879-11e8-9daf-5277a2bcc858.png)

**Comment by moradazizi** [comment]
@VesaJuvonen, we are having the same problem in our tenant now for a week. I have tried "Set-SPOHideDefaultThemes $false" but no results so far. 
Last week I added a test theme to the palette. After choosing it, it showed up, but the themes in the Change the look, disappeared.  Any solution?
