### ISSUE TITLE
Adding helloworld-webpart.spapp to my App Catalog, deploy option greyed out

### ISSUE THREAD

**Issue by MLDBlueMetal** [SharePoint/sp-dev-docs#245]
When I add my helloworld-webpart.spapp to my app catalog I do not get prompted to deploy the file when I drag and drop it and the ribbon command to deploy is greyed out.  I am logged in as tenant administrator and I created both the app catalog and my developer site with the same account.  What is the deal?

I have updated to SPx Drop 5 and it did fix the certificate issue using gulp serve.   Thank you for that.
#### Category
- [X ] Question
- [ ] Typo
- [ ] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

**Comment by patmill** [comment]
Did this work in a previous build on the same tenant?  Are you using a developer tenant (not site collection, but a developer tenant)?

**Comment by MLDBlueMetal** [comment]
I was on a business tenant not developer tenant.   There are so many steps to get this working that I must have missed that important piece of information.   

I have now added/deployed the file successfully to App Store on my o365 Developer Tenant.
![apps](https://cloud.githubusercontent.com/assets/20992569/19490955/39d4e392-953f-11e6-907d-7c328ef00301.PNG)

However when I add the app to a site, I see these error messages now when I try to add the web part to a page.   What did I miss now?    

This shouldn't be so hard :-(  
![error2](https://cloud.githubusercontent.com/assets/20992569/19490970/4d618280-953f-11e6-8603-b01f62f382ed.PNG)

![error](https://cloud.githubusercontent.com/assets/20992569/19490965/49ae3822-953f-11e6-8dd4-4c28b1f5fab9.PNG)

**Comment by patmill** [comment]
Fair point, and we plan on smoothing out the bumps.

To get around the issue you are currently seeing, create a publishing site collection (or a developer site collection).  These site collections don't have NoScript enabled (technically, they don't have the Add Customize Page permission removed).  There is a whole discussion to be had around NoScript and how the framework interacts with it (again - we have work items to make it work nicer with NoScript sites).

**Comment by MLDBlueMetal** [comment]
Well, getting closer.   Any help with this one now?

![hellomld](https://cloud.githubusercontent.com/assets/20992569/19494535/a27c2ffa-954d-11e6-8aa8-56179d9be280.PNG)

**Comment by patmill** [comment]
If you are following the labs, are you on this lab (http://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page) or this one (http://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/deploy-web-part-to-cdn)?

If you haven't deployed to a CDN, is gulp serve running?

**Comment by MLDBlueMetal** [comment]
Thank you for the links.  I see all of the dependency files are not bundled into the .spapp packaged file.  I will try running gulp with no browser.  I am not sure if this is just me but is the app packaging going to be simplified when moving from DEV (localhost) to a production server?  Could we have one file in config for all dependencies set by a variable instead of URLS?  in the example it would be awesome if we coykd change the host and CDN locations in one place to facilitate deoyment from DEV to staging and then eventuallu production?  All dependent files should point to the variable rather than a static URL.  Does that make sense?  Am I asking for too much?  :-)

**Comment by MLDBlueMetal** [comment]
I apologize for all typos!  On my phone

**Comment by patmill** [comment]
Just to make sure - is your original set of issues sorted out (your webpart is now working)?  Your other feedback is received and appreciated.

**Comment by MLDBlueMetal** [comment]
Yes this is now resolved.   I ran gulp serve --nobrowser after adding the app to my developer tenant and I was able to see the web part working in my dev site!    Thank you!!

**Comment by Rajesh-Pradhan** [comment]
Guys I'm still not able to see the Deployment window while adding .spapp file to App Catalog. It simply added with no pop up window

**Comment by mcmynn83** [comment]
Is the app package valid (ie under Valid App Package you see "Yes")?

**Comment by chakkaradeep** [comment]
@Rajesh-Pradhan Can you also confirm if you are on a Office 365 Developer Tenant?

**Comment by Rajesh-Pradhan** [comment]
@chakkaradeep Yes I'm on  Office 365 Developer Tenant

**Comment by Rajesh-Pradhan** [comment]
@chak
![capture1](https://cloud.githubusercontent.com/assets/15956887/20206493/c9d06a3c-a806-11e6-8fe1-64123e07f642.PNG)
karadeep @mcmynn83 Here is the screen i'm getting after uploading to App catalog

**Comment by patmill** [comment]
Hi @Rajesh-Pradhan - would you mind showing your tenant URL?  Alternately, you can email it to me at my username @microsoft.com  .  We need to make sure that you are on a developer tenancy, not a developer site collection.

**Comment by Rajesh-Pradhan** [comment]
Hi @patmill I have modify the view and i found "App Package Error Message" column but over there no information is found. Also due to policies I'm not bale to share my URL , but my URL looks like "https://xxxxxxxx.sharepoint.com/sites/apps/AppCatalog/Forms/AllItems.aspx" .

**Comment by webtechy** [comment]
Did you guys resolve this? I am seeing the same thing. I had a create a new App Catalog (presume this does not need to be a developer site collection, I don't recall seeing an option for that). Likewise, I got no pop-up saying to trust, "Valid App Package" is set to "No" and "App Package Error" is blank. I second  @MLDBlueMetal that it would be nice if by default all assets required as also packaged into the web part that is deployed rather than needing to setup CDN's.

**Comment by mauricionr** [comment]
But now the package is .sppkg

https://github.com/SharePoint/sp-dev-docs/wiki/Release-Notes-RC0#what-changed-in-this-drop

**Comment by mcmynn83** [comment]
@webtechy - you are not getting a pop-up saying to trust the app because it is not a valid app package.  One of two things is happening:
1.  The feature is not enabled on your tenant - Do you have first release set for your entire tenant?
2.  The app package is invalid... in which case you should have an App Package Error.  Most likely the problem is #1.

Please validate that First Release is set for your entire tenant... also if possible please send the URL of your site collection your are having issues with.

Thanks,
Graham

**Comment by paigeflourin** [comment]
Hello,

@mcmynn83 i am also encountering this error with my package, i followed this one step by step https://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page it works locally but when i try to deploy it to my app catalog, i get no error but the "valid app package" is set to no,

![capture](https://cloud.githubusercontent.com/assets/6951524/23010573/1c7d2468-f457-11e6-92b0-9a19e657186d.PNG)


i checked the tenant and First release is enabled and my account is part of it.


![capture](https://cloud.githubusercontent.com/assets/6951524/23010586/3b24d35c-f457-11e6-9871-dc87290c5885.PNG)

**Comment by webtechy** [comment]
Hi @paigeflourin, try adding the App Package Error to the columns in that view. Someone may correct me, but I don't think it works with only specific people, you need first release for the whole site collection.

**Comment by paigeflourin** [comment]
@webtechy Hi Ben, 
i added the field unfortunately there is no error.

![capture](https://cloud.githubusercontent.com/assets/6951524/23014044/5306fd0e-f468-11e6-8ec6-142032d344fc.PNG)

**Comment by webtechy** [comment]
Have you tried switching First Release on for everyone? In my experience this was needed, and I had to leave it for a bit and go and have a coffee before it started working.

**Comment by mcmynn83** [comment]
@paigeflourin - webtechy is correct, first release MUST be set for the entire org if you want to have app packages validate and be usable before GA. The behavior you are seeing is expected.

**Comment by mcmynn83** [comment]
@webtechy - Sounds like your issue has been resolved then?  You are correct, First Release settings take a while to propagate.  Unfortunately there is no way to check that the setting has propagated.

**Comment by webtechy** [comment]
(Would be nice to have an error message that told you that though ;-))

**Comment by mcmynn83** [comment]
I understand this causes grief... the good thing is it is only temporary.  Once the product is rolled out world wide for GA nobody will see this problem.  First Release basically turns on a feature that just straight up does not exist without it.  Therefore the reason you don't get a nice error message is the code has no idea that it is a possibly valid client side package, it just sees it as completely invalid 2013 app package.  Sorry about that.

**Comment by paigeflourin** [comment]
HEllo @webtechy  @mcmynn83  yeah first release  for everyone made it work. thanks guys!

**Comment by mcmynn83** [comment]
Excellent glad you were able to resolve the issue!

**Comment by Savan12791** [comment]
![image](https://cloud.githubusercontent.com/assets/26480786/24037225/0fcbc6ba-0b23-11e7-8942-ab34f12a82ac.png)

I have created a RSSFeed Webpart from Scratch its working fine on local workbranch but when i deployed its sppkg file to appcatalog and added it to webpart page its giving me the following error.
How to reslove it?

**Comment by webtechy** [comment]
Couple of points:

1. Run `gulp clean` before running `gulp build --ship`, `gulp bundle --ship` and g`ulp package-solution --ship`

2. Ensure you have set the CDN location correctly in the write-manifest.json,e.g. 

```
{
  "cdnBasePath": "https://grantthorntondev.sharepoint.com/sites/Development/SiteAssets/GrantThornton/"
}
```

3. Ensure you are deploying the DIST folder to the CDN location (check the F12 network tab where it is looking for the assets).

**Comment by Savan12791** [comment]
But i its also required the` temp\deploy` files.

**Comment by amarnathpoosala** [comment]
Hi I am also facing the same issue.  I am not able to drag and drop the .sppkg file in my app catalaog site collection onpremise trial version of sharepoint 2016. Even if I upload the file, I get the Valid App package value NO. Is there something I have to configure to be able to use sppkg files on Onpremise. Is that because trial version doesnt support this? or Only Online version supports spfx?  Thanks in advance.

**Comment by mcmynn83** [comment]
@amarnathpoosala  - SPFX is not currently supported in the on premises version of SharePoint.

**Comment by Rajesh-Pradhan** [comment]
Is SPFx now supporting SharePoint 2016 on Premise ?

**Comment by andrewconnell** [comment]
@Rajesh-Pradhan yup - https://dev.office.com/sharepoint/docs/spfx/sharepoint-2016-support
