### ISSUE TITLE
Dynamic Data : Problem with unregisterAvailableSourcesChanged

### ISSUE THREAD

**Issue by BraunJonathan** [SharePoint/sp-dev-docs#2728]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When i call the unregisterAvailableSourcesChanged method from the dynamicDataProvider object, the calback provided as argument should not be called anymore...

#### Observed Behavior

It seems to me that calling  unregisterAvailableSourcesChanged does not unregister the callback...

#### Steps to Reproduce
 I've got a page with several same webparts which all are providers and consumers of dynamic data for each other...

On my react component in the componentDidMount method i call the registerAvailableSourcesChanged with a callback.
On my componentWillUnmount method i call the unregisterAvailableSourcesChanged with the same callback.

My callback stays registered somewhere and each time i got back on the page, more callback are registered...

In the following example, props.context is the webpart context...
I have the same webpart twice  in the same page and the webpart implements IDynamicDataCallables

```javascript
public componentDidMount() {   
  this.props.context.dynamicDataProvider.registerAvailableSourcesChanged(this.registerDynamicDatasources.bind(this));
  }

public componentWillUnmount(){
  this.props.context.dynamicDataProvider.unregisterAvailableSourcesChanged(this.registerDynamicDatasources.bind(this));
}

private registerDynamicDatasources() : void {
  console.log("register dynamic datasources " + this.props.context.instanceId);
}

```

On the real code, the registerDynamicDatasources method gets all available sources to connect to them...

Thanks for your contribution! Sharing is caring.

**Comment by BraunJonathan** [comment]
[testDynamicData.zip](https://github.com/SharePoint/sp-dev-docs/files/2463663/testDynamicData.zip)
You can find here a  sample webpart to reproduce the problem.
You juste have to put the webpart twice on a site and look in the console  on the number of logs looking like "TEST register dynamic datasources" when leaving and coming back on the page
It is even worse when you leave the page to another site on the tenant.

Maybe ido not do things the right way, if so, please tell me what is wrong with my code ;-)

**Comment by VesaJuvonen** [comment]
This should be now solved with the GA release, but we would appreciate your input on confirming that.

**Comment by BraunJonathan** [comment]
Hi @VesaJuvonen 
Thanks for having a look at my problem but it seems the problem is still here...

**Comment by VesaJuvonen** [comment]
Thanks, @BraunJonathan  for coming back on this. If the issue is still with the 1.7, then the planned fix was not successful and we'll have a look on this.

**Comment by srideshpande** [comment]
@BraunJonathan - Thanks for reporting this issue. This issue should have been fixed. I just double checked and see it works as expected. Can you please retry?

I'm closing the issue. Please feel free to open a new one, if you still see the issue.
