### ISSUE TITLE
1000 log messages "Icon being re-registered. Ignoring duplicate registration." using Fabric React in SPFX webpart solution

### ISSUE THREAD

**Issue by frevds** [SharePoint/sp-dev-docs#2867]
I'm having a SPFX webpart solution using React and Fabric UI. 
In the browser log I get more than 1000 warnings about icons being re-registered. 
I attempted to deactivate these using the GlobalSettings for icons but that did not help. 

Is this normal or am I having some ill-configured packages? 

![image](https://user-images.githubusercontent.com/5341447/47876337-549e2880-de19-11e8-8d84-53c9cb2494d0.png)

**Comment by KingKangMSFT** [comment]
These warnings are normal. So don't worry  about it

**Comment by frevds** [comment]
If that is indeed the case for any solution made with Fabric in SharePoint, then Microsoft is not acting professionally here. We are developing solutions. It is hard to explain to our customers (big companies) to ignore 1000 ugly warnings in the log, and it is extremely annoying to have them in there (takes memory and time) and no way to disable them. If I want to debug my solutions in Edge, I have to wait 1 minute for my log messages to appear after all these warnings, due to the slow processing.

**Comment by salascz** [comment]
Agreed, those warnings are very annoying during development...

**Comment by frevds** [comment]
You mean they don't appear in production?

**Comment by kciabc** [comment]
Totally agree. These warnings suck up resources and lead to poor page load performance.

**Comment by pedropablo** [comment]
I think this is a SharePoint Online issue, because in "native" pages it also shows the warnings. Even the new sharepoint admin page shows them 
![shpadmin](https://user-images.githubusercontent.com/5614764/48154212-a7e6ff80-e28d-11e8-920c-c71b9abc2326.png)

**Comment by frevds** [comment]
Interesting @pedropablo, thanks for pointing that out. It seems this is happening with every clientside page (e.g. when creating a Site Page in Pages). Apparently whenever the Fabric React bundle is loaded, since the icons were registered before by SharePoint natively. The Fabric GlobalSettings defaults for icons should be adjusted so that these warnings don't appear on the console.

**Comment by kingfu** [comment]
Agree.  Needs to be a way to disable.  I tried the suggestion from this article: https://github.com/OfficeDev/office-ui-fabric-react/wiki/Using-icons but first option doesn't seem to work and second option won't compile.

**Comment by frevds** [comment]
As pointed out earlier this cannot possibly be done by us in the extension we control, since these warnings already occur on the SharePoint side when the ClientSidePage is loaded. This is what MS should add to their call to initializeIcons. 

Both calls compile for me, none have any effect. I tried the same using the GlobalSettings class.

**Comment by dzearing** [comment]
@frevds the problem is that `registerIcons` is being called multiple times. It is not pointless that there are complaints here; but something is causing an unanticipated behavior. 

Whatever information you have to repro would be useful. Trying to get a dev here to help out on the SP side.

**Comment by frevds** [comment]
@dzearing Yeah, a SP dev taking a look at it would be great. I do have these warnings in the log for a plain ClientSidePage (Site Pages library > New Site Page). Apparently SharePoint registers the icons on its own and then loads the Fabric UI react bundle separately and registering them again. What exactly goes on under the hood is anybody's guess. 

On the Fabric side - would it be possible to have a **time-based aggregation of these warnings**? Instead of having literally 1000+ messages of the same wording in the log for each icon one could put 1 message with 1000 icon names in it. Particularly in the Edge browser it takes more than 1 minute to actually poll all those warnings into the console (making debugging annoying, for every time you refresh the page you have to wait 1min to find your own log messages).

**Comment by frevds** [comment]
Great, looking forward to it.. which reminds me, this won't be coming straight into SharePoint anytime soon I'm afraid. But good to know that eventually it will.

**Comment by dzearing** [comment]
Separately, there are devs now investigating on the sppages side to identify root cause.

**Comment by dzearing** [comment]
The fix will be published in Fabric 6 tonight; I'm looking at cherrypicking into 5 and seeing if we can get that rolling if the devs investigating don't find the root cause sooner.

**Comment by MaheshakaMudli** [comment]
Fabric  6 is not supported in spfx 1.6+. Is there any other alternatives to get rid of these warnings as it is impacting the page performance in production.

**Comment by AteetAgarwal** [comment]
SP 2016 is using SPFx 1.1.0 and office-ui-fabric-react 2.31.0. This issue exist there too. What is its possible solution?

**Comment by magonzalezm** [comment]
I have the same problem, the more than 1000 warnings come from this js:  https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-11-09.013/office-ui-fabric-react-bundle_71d81bf8e2308355fb1b83074045e6a9.js
I use spfx with different versions 1.7 and 1.1.

**Comment by salascz** [comment]
The issue has been solved already on Fabric side. Now we have to wait till SharePoint guys updates their packages on their side...

**Comment by AteetAgarwal** [comment]
I followed the blog https://github.com/OfficeDev/officev-ui-fabric-react/wiki/Using-icons to fix the issue. SPFx v1.1.0 doesn't support these classes, so tried with v 1.7.0 but that doesn't solve the issue.

**Comment by salascz** [comment]
Well I got those warnings even for empty workbench page... 

Your issue might not be caused by your code. 

Actually, I do not know about any way, how to force the rest of the SharePoint page to use updated Fabric even when you use it for your code...

**Comment by frevds** [comment]
I'm glad to announce that of today the issue is gone. SharePointOnline released a new update yesterday (React16 and probably Fabric6) and also addressed this issue. I do no longer get any of these warnings, even on old pages and with Fabric5 custom solutions. Thanks to everybody involved for getting this solved so quickly.

**Comment by dzearing** [comment]
I believe they're stlil working through TypeScript updates first before Fabric 6, and that the cherrypicked fix in 5 got updated there.

**Comment by frevds** [comment]
@dzearing gotcha - console log in SharePoint Online: 

![image](https://user-images.githubusercontent.com/5341447/49696767-4c22d580-fbaf-11e8-9e48-8a115a6b3920.png)

Thanks for aggregating that one and saving us a lot of log space. 
I'm gonna close this ticket.

**Comment by MaheshakaMudli** [comment]
@dzearing , @frevds : We are facing this issue now in our tenant. In Edge, the browser hangs while this logs are been printed. We are using spfx 1.6 with react 15 and office fabric 5. Can this be resolved at our end in any way. Please see the screenshot below.

![image](https://user-images.githubusercontent.com/23700986/52714610-505cdc00-2fc0-11e9-8839-c4ce9dfb6a4a.png)

**Comment by frevds** [comment]
@MaheshakaMudli Hm no, you're not facing _that_ issue. Originally we had 1483 individual messages in the log - your screenshot indicates that these messages are already aggregated into one, which was the improvement ("Some icons were re-registered […] + 1483 more"). There will always be a gazillion other messages in the log, and only Edge seems to have a problem handling many log messages when the F12 console is open, which it streams in an torturous slow way (1 chunk of 10 each second only or so).

**Comment by MaheshakaMudli** [comment]
@frevds: currently this is in production environment and lot of our clients use edge browser resulting in compliants. Is there any workaround available to cope with it in edge.

**Comment by frevds** [comment]
@MaheshakaMudli Your customers rarely have the F12 console open. So this can't be the issue. In other words - Logging does _not_ happen if the F12 console isn't (and was never) opened for the page - the code runs without debug instructions in an optimized profile. You should investigate what else might cause the problems during load, maybe some synchronously loaded resources.

**Comment by frevds** [comment]
@dzearing Could the browser freeze described by @MaheshakaMudli have anything to do with the way the messages are aggregated using a timeout? Indeed this is independent of whether the console is open or not, and on rather slow computers this could cause issues if resetting the timeout is a costy process that has to be executed 1483 times.
