### ISSUE TITLE
Loading indicator message not displayed (generator v1.0.2)

### ISSUE THREAD

**Issue by waldekmastykarz** [SharePoint/sp-dev-docs#297]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
When using the web part loading indicator, the specified loading message should be displayed.

#### Observed Behavior
When calling the loading indicator in the web part **onInit** method, instead of the specified loading message, the standard _Loading [web part title]..._ message is displayed.

#### Steps to Reproduce
Create a new web part. To the web part class add the following code:

```ts
protected onInit(): Promise<void> {
  return new Promise<void>((resolve, reject) => {
    this.context.statusRenderer.displayLoadingIndicator(this.domElement, 'data');

    setTimeout((): void => {
      this.context.statusRenderer.clearLoadingIndicator(this.domElement);
      resolve();
    }, 10000);
  });
}
```

Instead of showing _Loading data..._ the web part shows _Loading [web part title]..._.

**Comment by manishgarg1** [comment]
Hi @waldekmastykarz, I think this is fixed. Can you still repro it ? If not, could you please close the issue?

**Comment by waldekmastykarz** [comment]
I've just checked and the issue is still there. Verified using the exact same repro steps as mentioned above.

**Comment by andrewconnell** [comment]
Confirmed I see the same thing, but not just within the `OnInit()` method... I see it in the `render()` method as well. Might be bigger issue with the rendering... see bug #696 I just added.

**Comment by patmill** [comment]
As mentioned in #696 - this should be resolved.
