### ISSUE TITLE
Deployment failed when trying to implement without Office CDN

### ISSUE THREAD

**Issue by DanielKaupp** [SharePoint/sp-dev-docs#3438]
Hi,

I'm facing the same issues as in #3358. Due to some restrictions, we do not have CDN enabled. But it should (according to the note) also be working without, by just uploading the assets to the app catalog.
I do not see a solution for #3358. If the problem could be resolved, please tell me how.

What can I or my administrator do to troubleshoot this?

Thx, Daniel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e911c86d-76ea-3a23-f98e-7ad7b804a408
* Version Independent ID: 9c7748a8-3e63-19ed-4e69-15136603f302
* Content: [Host your client-side web part from Office 365 CDN (Hello World part 4)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn)
* Content Source: [docs/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by vman** [comment]
Hi @DanielKaupp yes the SPFx webparts do work even if the Office 365 CDN is disabled. In that case, the js files should be served form the App Catalog site collection. 

What exact error are you getting? Could you please post more details along with screenshots etc.?

**Comment by DanielKaupp** [comment]
Hi @vman, 
![grafik](https://user-images.githubusercontent.com/3942311/52697307-7c04a580-2f71-11e9-933c-a88e31a75aa2.png)

The error says: "Fehler bei der Bereitstellung. Korrelations-ID: 2e3bbf9e-b03e-0000-6139-a68fd7396075"
That would translate to: "Error while deploying. Correlation-ID: ..."

Upfront I tried gulp serve, gulp build, gulp bundle --ship, gulp package --ship

How can i troubleshoot this? Does the correlation ID correlate to anything?

Thanks, Daniel

**Comment by DanielKaupp** [comment]
Hi @vman, 
![grafik](https://user-images.githubusercontent.com/3942311/52697307-7c04a580-2f71-11e9-933c-a88e31a75aa2.png)

The error says: "Fehler bei der Bereitstellung. Korrelations-ID: 2e3bbf9e-b03e-0000-6139-a68fd7396075"
That would translate to: "Error while deploying. Correlation-ID: ..."

Upfront I tried gulp serve, gulp build, gulp bundle --ship, gulp package --ship

How can i troubleshoot this? Does the correlation ID correlate to anything?

Thanks, Daniel

**Comment by vman** [comment]
@DanielKaupp you have close the issue so I thought it was fixed? If not, can you updload your .sppkg file somewhere and I can take a look?

**Comment by DanielKaupp** [comment]
@vman, sorry I was mislead by the "close and comment" caption of the button. The problem still persists.

Please find the file attached:
[hello-world.zip](https://github.com/SharePoint/sp-dev-docs/files/2864978/hello-world.zip)

Thanks, Daniel

**Comment by vman** [comment]
I am able to upload the app package without any issues: 
![image](https://user-images.githubusercontent.com/173794/52788803-f4469600-3059-11e9-8b3b-e2a096b2fbaa.png)

Have you tried it on any other tenant?

**Comment by DanielKaupp** [comment]
No, I only have one tenant available. Do you have a CDN active on your tenant?

The original deploy with the local sources (where gulp serve needs to run locally) worked without problems.

**Comment by vman** [comment]
I don't have the CDN enabled:
![image](https://user-images.githubusercontent.com/173794/52789969-4806ae80-305d-11e9-9f72-c3451ae4f664.png)

**Comment by DanielKaupp** [comment]
ok... do you have any ideas, where the problem could be located?

**Comment by vman** [comment]
Have you tried removing the app from the App Catalog, the site recycle bin, the admin recycle bin and then try to upload again? 
Also try creating a different SPFx app with the latest generator and try uploading it.

**Comment by DanielKaupp** [comment]
I tried removing it totally, but it shows the same issue. What do you mean by latest generator?

**Comment by patmill** [comment]
Also, the next time you try and get an error, can you post the correlation ID, and your tenant URL?

As far as trouble shooting goes though, can you make sure that you have a client side asset library in your app catalog, and that you have permissions to it?  The URL should be https://<yourTenant>/<appCatalogSiteUrl>/ClientSideAssets/AllItems.aspx
