### ISSUE TITLE
Office UI Fabric React Getting Started Example

### ISSUE THREAD

**Issue by JorisZzz** [SharePoint/sp-dev-docs#3648]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
I can't get the DocumentCard demo to run.

#### Observed Behavior
Typescript error while building

#### Steps to Reproduce
I am going through the building SharePoint client-side webparts tutorials.
Followed the steps on https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/use-fabric-react-components

After this code change, the solution does not run anymore:
import {
  DocumentCard,
  DocumentCardPreview,
  DocumentCardTitle,
  DocumentCardActivity,
  IDocumentCardPreviewProps
} from 'office-ui-fabric-react/lib/DocumentCard';

[10:31:07] Error - [tsc] node_modules/@uifabric/merge-styles/lib/IStyleSet.d.ts(15,67): error TS1005: ';' expected.
[10:31:07] Error - [tsc] node_modules/@uifabric/merge-styles/lib/IStyleSet.d.ts(15,114): error TS1005: '(' expected.
[10:31:07] Error - [tsc] node_modules/@uifabric/merge-styles/lib/IStyleSet.d.ts(15,136): error TS1005: '(' expected.
[10:31:07] Error - 'tsc' sub task errored after 2.8 s
 exited with code 2

**Comment by bcameron1231** [comment]
Hi, can you provide some information of your environment for us?

- SharePoint Version
- SPFx Version 
- Node Version

**Comment by JorisZzz** [comment]
I am using an Office365 developer tenant, but the error occurs in my local environment; NodeJS  v8.15.1 / Yeoman v2.0.5 on Windows 10.

Here's my package.json contents:
{
  "name": "documentcardexample-webpart",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "1.8.0",
    "@microsoft/sp-lodash-subset": "1.8.0",
    "@microsoft/sp-office-ui-fabric-core": "1.8.0",
    "@microsoft/sp-property-pane": "1.8.0",
    "@microsoft/sp-webpart-base": "1.8.0",
    "@types/es6-promise": "0.0.33",
    "@types/react": "16.4.2",
    "@types/react-dom": "16.0.5",
    "@types/webpack-env": "1.13.1",
    "office-ui-fabric-react": "^6.157.3",
    "react": "16.7.0",
    "react-dom": "16.7.0"
  },
  "resolutions": {
    "@types/react": "16.4.2"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.8.0",
    "@microsoft/sp-tslint-rules": "1.8.0",
    "@microsoft/sp-module-interfaces": "1.8.0",
    "@microsoft/sp-webpart-workbench": "1.8.0",
    "@microsoft/rush-stack-compiler-2.7": "0.4.0",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2"
  }
}

**Comment by patmill** [comment]
The problem is that the sample is accessing OUIFR w/o referencing it package.json, so it's getting the wrong version.  I'll update the tutorial documentation.

**Comment by patmill** [comment]
Thanks for the info - it should be fixed in a few minutes when the updates are applied.

**Comment by chinthaka321** [comment]
What is OUIFR w/o means?

**Comment by JorisZzz** [comment]
I have added "office-ui-fabric-react": "6.143.0" to the dependencies in package.json, but the same error remains.

**Comment by bcameron1231** [comment]
Did you re-update the node packages? The node_module was already installed with the wrong version. You'll need to update to 6.143.0 in your package.json, and then update your node module accordingly.

**Comment by JorisZzz** [comment]
I did run npm install, and then restarted VS Code.
When I got the same error I then deleted the whole project folder and restarted from scratch. Same result.

**Comment by chinthaka321** [comment]
Can you try following package.json and see. Check the version of fabric ui and rush-stack-compiler.
{
  "name": "office-fabric-ui",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "react": "16.7.0",
    "react-dom": "16.7.0",
    "@types/react": "16.4.2",
    "@types/react-dom": "16.0.5",
    "@microsoft/sp-core-library": "1.8.0",
    "@microsoft/sp-property-pane": "1.8.0",
    "@microsoft/sp-webpart-base": "1.8.0",
    "@microsoft/sp-lodash-subset": "1.8.0",
    "@microsoft/sp-office-ui-fabric-core": "1.8.0",
    "@types/webpack-env": "1.13.1",
    "@types/es6-promise": "0.0.33",
    "office-ui-fabric-react": "5.132.0"
  },
  "resolutions": {
    "@types/react": "16.4.2"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.8.0",
    "@microsoft/sp-tslint-rules": "1.8.0",
    "@microsoft/sp-module-interfaces": "1.8.0",
    "@microsoft/sp-webpart-workbench": "1.8.0",
    "@microsoft/rush-stack-compiler-2.7": "0.4.0",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2"
  }
}

**Comment by joselarios** [comment]
Experiencing the same error messages above, following the same "Steps to reproduce".

Changing the package.json office-ui-fabric-react dependency to "6.143.0" (as per the updated instructions) does not remove the error messages. However changing the office-ui-fabric-react version to "5.132.0" does remove the messages.

Is version "6.143.0" not meant to be supported?

Is the official solution to use the "5.132.0" version?

**Comment by patmill** [comment]
The documentation reads "5.132", which works with the default compiler, etc.  Newer versions of fabric (like 6.143) require updated versions of the compiler.

Are you seeing a different version in the docs?

**Comment by JorisZzz** [comment]
"changing the office-ui-fabric-react version to "5.132.0" does remove the messages."
This works for me as well. Thank you joselarios!

I did not see this requirement anywhere in the tutorial.
