### ISSUE TITLE
Get-PnPTenantSite throws error 'The request uses too many resources.'

### ISSUE THREAD

**Issue by advdberg** [SharePoint/sp-dev-docs#3765]
#### Category
- [ ] Question
- [ ] Typo
- [X] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Get the tenant site with Get-PnPTenantSite without error

#### Observed Behavior
Since this morning we get almost everytime the message 'The request uses too many resources.' on getting the tenant site

Sample tenant: ctbteamdev
But also on other tenants we intermittently saw the same behaviour since last night

#### Steps to Reproduce

Execute the following PowerShell
`$devcreds = Get-Credential`
`$newSiteUrl = 'https://xxx.sharepoint.com/sites/modernteamsite'`
`$adminUrl = 'https://xxx-admin.sharepoint.com'`
`Connect-PnPOnline -Url $adminUrl -Credentials $devcreds`
`$site = Get-PnPTenantSite -Detailed -Url $newSiteUrl`

**Comment by siata13** [comment]
Same behaviour on my tenant. Not only Get-PnPTenantSite but also received it for other commands like 'Apply-PnPTemplate'.

**Comment by poikjo** [comment]
I'm seeing this too a lot. Sometimes error message is "Exception has been thrown by the target of an invocation."

**Comment by OliverZeiser** [comment]
It is not a PnP Issue. Same thing happens with the official SharePoint Online Management Shell using Get-SPOSite CMD. So it is a general SharePoint Online Issue. We are also seeing many tenants beeing affected by this issue.

**Comment by yborghmans** [comment]
Having the same issues with doing CSOM calls to get site properties
var site = tenant.GetSitePropertiesByUrl(url, false);
tenantContext.Load(site, s => s.Status);
tenantContext.ExecuteQueryRetry(); => ERROR
 var status = site.Status;

**Comment by BigBd1** [comment]
Same behavior on my tenant since yesterday. FYI the code throwing this exception is 
`tenantContext.SetSiteProperties(newSiteContext.Web.Url, noScriptSite: false);`
There is no previous content loading and **tenantContext** is a _Microsoft.Online.SharePoint.TenantAdministration.Tenant_ from _Microsoft.Online.SharePoint.Client.Tenant_ object instance.
This bug seems to be random...

**Comment by VesaJuvonen** [comment]
Thanks for reporting @advdberg. Thanks, @OliverZeiser for confirming that this also happens outside of PnP components, which is important for troubleshooting and repro. Also thanks to others for confirming the different scenarios where things happen. This is really helpful information. 

We are currently investigating and hopefully can work a solution fast.

**Comment by VesaJuvonen** [comment]
Please note that if someone is facing similar issues on other APIs, please add them on this thread, so that we can also confirm that the upcoming fix will be working properly.

**Comment by MaximOvodok** [comment]
I want to keep your attention on the same error when you try to create site collection by the code:
`var op = tenant.CreateSite(properties);
tenantContext.Load(op, o => o.IsComplete);
tenantContext.ExecuteQuery();
`
Sometimes I get error 'Exception has been thrown by the target of an invocation'

**Comment by DRamalho92** [comment]
I'm seeing to the message "Exception has been thrown by the target of an invocation."

**Comment by VesaJuvonen** [comment]
@DRamalho92 can you share what did you do for getting this exception... which API, cmdlet or UI functionality was used for seeing the exception. Thx.

**Comment by DRamalho92** [comment]
@VesaJuvonen When using the PNP PowerShell commnad  Get-PnPTenantSite

Having the this exception:

Exception has been thrown by the target of an invocation.
At :line:1 char:1
+ G <<<< et-PnPTenantSite

**Comment by zrosenfield** [comment]
@DRamalho92 or anyone else; we can speed up the resolution if someone is willing to give us the FQDN of the tenant they are hitting this on.  Otherwise, we'll have to work through to get a repro which will slow us down.  Any chance someone wants to DM me on twitter at @zrosenfield with their FQDN so i can pass it along?

**Comment by zplume** [comment]
@zrosenfield I can't DM you on Twitter, are your Twitter DMs disabled?

**Comment by zrosenfield** [comment]
@zplume i think it's set so you have to follow me to DM me...  I'll try to look at my settings but you can give that a shot at the same time

**Comment by zplume** [comment]
I am following you already :)

Thanks

**Comment by zrosenfield** [comment]
@zplume first, thanks :).  second, i think i fixed it... try now

**Comment by zplume** [comment]
@zrosenfield - yes, that fixed it, I have DM'd

Thanks!

**Comment by DRamalho92** [comment]
@zrosenfield I still have the error, I've sent a DM on twitter.

**Comment by sebastienlevert** [comment]
Just tested this and got the same on another tenant. Simply using Get-PnPTenantSite on an infinite loop executing this command every 15 seconds and it fails 1 time out of 10, approximately.

**Comment by fredericklin** [comment]
We are getting these as well with some Powershell scripts.  We currently have our tenants relaxed for throttling as well for tenant-to-tenant SPO migrations.

**Comment by mmsharepoint** [comment]
I saw this on one of my customers tenants (not on PRD luckily where nearly the same cmdlets run against) since yesterday especially with Set-PnPTenantSite cmdlet.
Although in same runbook scripts I also use above mentioned Apply-PnPTemplate that cmdlet always went fine, for me it looked like only occuring under a (PnP) cennection to admin site but that's an assumption only from our scenario.

**Comment by desmay** [comment]
I've getting reports of similar error in SPMT tool at customer today

**Comment by zrosenfield** [comment]
Following up for folks--this issue is now fixed worldwide (as of roughly 4:30pm PST).  Thanks to everyone who shared a tenant for investigation!  Huge help in closing this out quickly.

**Comment by advdberg** [comment]
I can confirm we don't get the error anymore, thanks for the quick response!

**Comment by VesaJuvonen** [comment]
Thanks to everyone for your input around this issue and shared the needed insights for resolution.
