### ISSUE TITLE
Apply button disabled after changing the property pane dropdown

### ISSUE THREAD

**Issue by estruyf** [SharePoint/sp-dev-docs#46]
When changing the dropdown in the property pane, this doesn't trigger the Apply button to get enabled like it is for other fields.

Here is an example of what is going on:

![search-wp-spfx-dropdown](https://cloud.githubusercontent.com/assets/2900833/17837713/c0da4862-67ba-11e6-87a5-d0ae9aaf37aa.gif)

**Comment by pgonzal** [comment]
VSO 239943

**Comment by srideshpande** [comment]
Yeah, this is a known issue. This will be fixed in the next release. Thanks for pointing it out though.

**Comment by srideshpande** [comment]
Dropdown disable/enable feature is now fixed and will be in the next drop.

**Comment by IntranetFactory** [comment]
@srideshpande What is a "drop" ?

**Comment by estruyf** [comment]
@srideshpande it's indeed fixed in the latest version.

**Comment by curtis-hennessy-rp** [comment]
@srideshpande I am still getting this issue, running on the latest version.

**Comment by srideshpande** [comment]
Hello @curtis-hennessy-rp - Thanks for the feedback. I just verified with in-house web parts and I am not seeing the issue. Could you please show/share how you are building the property pane configuration object which you pass it to the framework? and also did you see this issue in the latest release? or it was never fixed for you?
