### ISSUE TITLE
ListViewCommand: event.selectedRows not updating

### ISSUE THREAD

**Issue by jordyvanbremen** [SharePoint/sp-dev-docs#4769]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Our ListViewCommand buttons are not working anymore. When selecting a specific item in a list and clicking our command button, at first there is no issue. When selecting another item in the list and then clicking the command button, event.selectedRows is still referring to the item that was selected initially. Only when I deselect an item before selecting another item, the selectedRows is showing the actual selected item. If I jump from Item 1 to Item 2 (without deselecting Item 1), selectedRows is not updated accordingly.

#### Observed Behavior

When selecting an item in the list, event.selectedRows should be updated accordingly.

#### Steps to Reproduce

- Create a new ListView command extension
- run gulp serve
- select an item in the list (i.e. Item 1)
- select another item in the list (i.e. Item 2)
- check event.selectedRows (it refers to Item 1)

See also this video repro: https://1drv.ms/v/s!AqmJ4PFCanuAnehX6Szz_7IS4Up1KQ

I'm logging the selected item ID from the onExecute method.
![image](https://user-images.githubusercontent.com/18749222/66911670-94b6e500-f043-11e9-8875-0511dbadefa9.png)

my versions:
![image](https://user-images.githubusercontent.com/18749222/66911523-4275c400-f043-11e9-9507-4f1de3546d7e.png)

**Comment by richardpoyner** [comment]
Having the same issue here.
OnExecute triggers only when the number of selected items has changed.
So 1 item and selecting 2 will trigger.
But selecting 1 item and then directly selecting another then there is no trigger.

**Comment by patrikhellgren** [comment]
I am also seeing the same issue.
Tenant in targeted release.

**Comment by ltdu** [comment]
We are having the same issue - contents of event.selectedRows changes only if amount of selected rows in view changes. 

Additionally tested with simple solution based on 1.9.1 and could reproduce this issue on both SR and TR rings.

**Comment by patmill** [comment]
Thanks for the heads up.  I reached out to the team, and they found the issue.  They are working on a fix.

**Comment by jhamoud** [comment]
Do we have an estimated timeline on the fix. I'm surprised a bug with this level of severity hasnt been addressed yet. We have users thinking they're executing a command on one item where in fact SharePoint is executing the command on a completely different item. It's basically wrecked havoc on our environment and there's now way to prevent it from happening.

**Comment by 23W** [comment]
@jhamoud 
Looks like events work correct if command is registered for both ContextMenu and CommandBar:
```
<CustomAction Location="ClientSideExtension.ListViewCommandSet"/>
```

**Comment by jasonalex13** [comment]
> @jhamoud
> Looks like events work correct if command is registered for both ContextMenu and CommandBar:
> 
> ```
> <CustomAction Location="ClientSideExtension.ListViewCommandSet"/>
> ```

That's not the case in my environment at least - I already had it set up for both and I've had this same issue. I just double checked and it hasn't come good yet.

**Comment by 23W** [comment]
Maybe there is other way how to detect right selection in list view, e.g. via DOM ?

**Comment by 23W** [comment]
@patmill Do you have some info when this bug will be fixed?

**Comment by hamedy** [comment]
> Maybe there is other way how to detect right selection in list view, e.g. via DOM ?
> How about such code?
> 
> ```ts
> import * as $ from 'jquery';
> 
> // optional filtering item by name
> function filterItem(itemName: string) : boolean {
>     return true;
> }
> 
> // find the first selected item name in list view (in both view mode: records table and tiles)
> export function getSelectedItemName(): string {
>     let selectedItemName: string = '';
>     
>     const selectedRows = $("[role='grid'] .is-selected[role='row']:first");
>     if (selectedRows.length > 0) {
>         selectedRows.find('button.ms-Link')
>                     .each(function () { 
>                         if (filterItem(this.innerText)) {
>                             selectedItemName = this.innerText;
>                             return false;
>                         }
>                     });
>     }
>     else {
>         const selectedTiles = $("[role='list'] .ms-Tile--isSelected:first");
>         if (selectedTiles.length > 0) {
>             selectedTiles.find('.ms-Tile-nameplate [data-automationid="name"]')
>                          .each(function () {
>                              if (filterItem(this.innerText)) {
>                                  selectedItemName = this.innerText;
>                                  return false;
>                              }
>                          });
>         }
>     }
> 
>     return selectedItemName;
> }
> ```

done such things in the past and it was never a good idea. DOM might change and we have no control over that. For now I'm going to prompt the user with the selected file info when they trigger the extension and ask them to use radio buttons if selected item is wrong. Hoping that a fix will be rolled out soon.

**Comment by matthong** [comment]
We are having the same issue. Is there an estimated timeline on the fix?

**Comment by 23W** [comment]
Can we use JSOM to detect real selection in the list? 
E.g. `SP.ListOperation.Selection.getSelectedItems()`

**Comment by zaiby** [comment]
Sort of workaround:
To bypass this issue in a good manner we have created a field customizer containing our own dropdownmenu:
![image](https://user-images.githubusercontent.com/5594235/68578196-d46dc280-0471-11ea-8f4e-6874383d7ba9.png)

And then you can get the id using 
![image](https://user-images.githubusercontent.com/5594235/68578339-14cd4080-0472-11ea-9c91-e1f1a43bef52.png)

**Comment by 23W** [comment]
@zaiby 
Could you please provide bit more information. Why dropdown menu? How can field customizer can help list view commands set, it's different extensions?

**Comment by hamedy** [comment]
> Sort of workaround:
> To bypass this issue in a good manner we have created a field customizer containing our own dropdownmenu:
> ![image](https://user-images.githubusercontent.com/5594235/68578196-d46dc280-0471-11ea-8f4e-6874383d7ba9.png)
> 
> And then you can get the id using
> ![image](https://user-images.githubusercontent.com/5594235/68578339-14cd4080-0472-11ea-9c91-e1f1a43bef52.png)

nice try but you're gonna need to deal with another bug there. https://github.com/SharePoint/sp-dev-docs/issues/4656

**Comment by zaiby** [comment]
> > Sort of workaround:
> > To bypass this issue in a good manner we have created a field customizer containing our own dropdownmenu:
> > ![image](https://user-images.githubusercontent.com/5594235/68578196-d46dc280-0471-11ea-8f4e-6874383d7ba9.png)
> > And then you can get the id using
> > ![image](https://user-images.githubusercontent.com/5594235/68578339-14cd4080-0472-11ea-9c91-e1f1a43bef52.png)
> 
> nice try but you're gonna need to deal with another bug there. #4656

Thanks for the heads up 😂

**Comment by zaiby** [comment]
> @zaiby
> Could you please provide bit more information. Why dropdown menu? How can field customizer can help list view commands set, it's different extensions? By the way, looks like field customizer doesn't work in Tiled View mode, so u can't collect items ids in this mode view field customizer.

I can see that this may not work for everybody but the code was basically just copy paste to the new solution and then some code changes very few places. But that is what we have done as we have a go live in few days.

**Comment by jhamoud** [comment]
I'm not clear on why we're trying to hack around a bug that has the potential to create complete chaos. I dont think the dev team understand the magnitude of this. Think of GDPR - data privacy. If the user acts in a way that induces the bug (which is highly likely) we could end up deleting the wrong record. Reporting we deleted the right one (because sharepoint confirmed a record deletion) and incorrectly report to compliance about that fact. 

Has anyone tried to go through MS Support on this? Is there another route to escalate the severity on this? Doesnt seem like Triage assigns a severity.

**Comment by 23W** [comment]
@jhamoud 
This bug's status was changed from "triage" to "to be reviewed" more than 20 days ago, so dev team admit that it's a bug but looks like they DO NOT THINK it's critical or severe issue! 
From other side, internal SP client scripts work excellent, it means that correct solution exists. I've asked SPFx team to give as workaround for this issue (https://github.com/SharePoint/sp-dev-docs/issues/4878) but only ms-bot has visited this complain.

Do I have other way than try to find workaround by myself?

P.S.: not only event.selectedRows is broken, SPFx selection processing has broken completely: https://github.com/SharePoint/sp-dev-docs/issues/4828!

**Comment by 23W** [comment]
@andrewconnell 
Looks like I've found one bug place:
SP script `listview-host-assembly_default` methods `refresh` and ``.  This method is called every time when selection is changed.
Look at code:
```js
return e.prototype.refresh = function (e) {
  if (!this._lastSelectedRows || this._lastSelectedRows.length !== e.length) {
    this._lastSelectedRows = e.slice(0);
    var t = {
      selectedRows: e.map(function (e) {
        return e.accessor
      })
    };
    this._commandSet.onListViewUpdated(t),
    this._updateAdapter()
  }
},
e.prototype.execute = function () {
    var e = {
      commandId: this.commandId,
      itemId: this.commandId,
      selectedRows: (this._lastSelectedRows || [
      ]).map(function (e) {
        return e.accessor
      })
    };
    this._commandSet.onExecute(e)
},
```
So as you see `onExecute()` is called with selected rows collection from `_lastSelectedRows`. Member `_lastSelectedRows ` is updated ONLY in `refresh` method before calling `onListViewUpdated()`. 
But! refresh method skips all calls if `_lastSelectedRows` has the same **count** as argument! So even if new selection is different but has still the same selected items count it will be ignored! 
I understand, you tries to eliminate redundant calls, but refresh method HAVE TO correctly compare stored `_lastSelectedRows` array and new selection array, not only by count but by values also.

**Comment by patmill** [comment]
The fix has been made by the owning team and will be rolling out with the next update.  i'll updatre when we have exact dates for that.

**Comment by matthong** [comment]
> The fix has been made by the owning team and will be rolling out with the next update.  i'll updatre when we have exact dates for that.

That's good news. Thanks!

**Comment by patmill** [comment]
OK, the fix should start rolling tomorrow to a small slice of tenants, then should get to 100% by next Wed.

**Comment by russgove** [comment]
Hey , as a workaround , it  seems to work  if you add the ID column to the view.

**Comment by 23W** [comment]
> The fix has been made by the owning team and will be rolling out with the next update. i'll updatre when we have exact dates for that.

It's excelent news. By the way, `refresh` method is not called at all when user clicks subfoder in list and browses it. Has it fixed also?

**Comment by oliverlp** [comment]
Could this other bug be related? https://github.com/SharePoint/sp-dev-fx-extensions/issues/267 (ListView Command Set: event.selectedRows returns wrong ID, when there is a pinned document in the library). Any hope it gets also solved by this rollout?

**Comment by cwdata** [comment]
Ok, it's now "next week Thursday" and the issue still persists. If the fix actually has been rolled out 100% on Wednesday it didn't fix it...

**Comment by sukumarraju** [comment]
This bug is still outstanding.

Could you provide an update please.

**Comment by patmill** [comment]
So unfortunately the fix for this issue is in the same build that contains the full fabric 7 rollout (see issues around css styling, etc.).  We have backported the command set fix and will either release a patched build or an updated newer build shortly.

**Comment by EddieE79** [comment]
Still having same issue - Any updates on this?

**Comment by oliverlp** [comment]
Hi.
It started working again for me yesterday.
It has been a big big problem during all these weeks. It has been difficult to explain the situation for my clients. It has taken much more time than I could guess. 
Curious to know how you have managed / best workarounds?

**Comment by patmill** [comment]
The build that contains this fix is finally out.

**Comment by cwdata** [comment]
Can confirm that this is now fixed in our tenant as well.

**Comment by VesaJuvonen** [comment]
thx @cwdata for confirming the roll out to your tenant. Closing this one as fixed for now based on that.
