### ISSUE TITLE
Random 500 internal server errors with different APIs and operations at SharePoint Online

### ISSUE THREAD

**Issue by advdberg** [SharePoint/sp-dev-docs#4924]
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Template is applied without errors (or at least with detailed errors)

#### Observed Behavior
We get an Intermittant 500 server error on applying a template with the following tracelog:

```
powershell.exe Information: 0 : 2019-10-08 14:40:40.6587    [OfficeDevPnP.Core]    [0]    [Information]    Adding field (382aae1d-7054-4b5d-85ca-ead7dfdd96f0) to content type (0x01010043443884AE06CF4D9F9C2D75C47BF75A).    0ms   
powershell.exe Information: 0 : 2019-10-08 14:40:42.7683    [OfficeDevPnP.Core]    [0]    [Information]    Adding field (eea8f2b4-9508-46a0-9f42-69008561a746) to content type (0x01010043443884AE06CF4D9F9C2D75C47BF75A).    0ms   
powershell.exe Error: 0 : 2019-10-08 14:40:42.8361    [OfficeDevPnP.Core]    [0]    [Error]    ExecuteQuery threw following exception: System.Net.WebException: De externe server heeft een fout geretourneerd: (500) Interne serverfout.
   bij System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   bij System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Microsoft.SharePoint.Client.SPWebRequestExecutor.<ExecuteAsync>d__0.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext().    0ms   
powershell.exe Information: 0 : 2019-10-08 14:40:42.8371    [Content Types]    [15]    [Debug]    Code execution scope ended    115033ms    57b414c0-2d01-471d-b956-b5bab9c3667f
powershell.exe Information: 0 : 2019-10-08 14:40:42.8371    [Provisioning]    [15]    [Debug]    Code execution scope ended    168283ms    57b414c0-2d01-471d-b956-b5bab9c3667f
```

#### Steps to Reproduce
execute the following PowerShell:
``
Apply-PnPProvisioningTemplate -Path "C:\temp\SiteTemplate(1).xml" -Verbose
``

**Comment by jeremyitprofessional** [comment]
Could this also be giving problems with get-pnpprovisioningtemplate?
Got the same internal server errors, with also it says the home page could not be found, related?
Script:
`pushd $saveDir -ErrorAction SilentlyContinue


# verbinding maken naar de template site
Write-Host "Connecting to: $siteURL" -ForegroundColor Yellow
Connect-PnPOnline -Url $siteURL -Credentials $cred
Write-Host "Connected!" -ForegroundColor Green

$web = Get-PnPWeb
$sourceSite = $web.ServerRelativeUrl
 
#Get all pages in the site pages library
$pages = Get-PnPListItem -List $library
 
#Save current homepage
$currentHomePage = Get-PnPHomePage
$pagesList = New-Object System.Collections.Generic.List[System.Object]
$pageNumber = 1
 
foreach ($page in $pages) {
    if ($page.FileSystemObjectType -eq "File") {
        $pagePath = $page.FieldValues["FileRef"]
        $pageFile = $pagePath -replace $sourceSite, ""
        $pageTemplate = $pageFile -replace "/SitePages/", "" -replace ".aspx", ".xml"
        $pagesList.Add($($pageTemplate -replace "./TemplateWithPages", ""))	
		
        #set current page as home page
        Set-PnPHomePage -RootFolderRelativeUrl ($pagePath -replace ($sourceSite + "/"), "")
		
        Write-Host ("Saving page #" + $pageNumber + " - " + $pageTemplate)
		
        if ($pageNumber -eq 1) {
            Get-PnPProvisioningTemplate -Out $($saveDir + "\" + $pageTemplate) -PersistBrandingFiles
        }
        else {
            Get-PnPProvisioningTemplate -Out $($saveDir + $pageTemplate) -Handlers PageContents
        }
		
        $pageNumber++
    }
}
 
$pagesList.ToArray()
 
#apply default default homepage
Set-PnPHomePage -RootFolderRelativeUrl $currentHomePage
 
#copy base template 
Copy-item -path ($saveDir + $pagesList[0]) -destination ($saveDir + "\pnpprov-Commissies.xml")
 
#open main xml
$mainFile = [xml][io.File]::ReadAllText($($saveDir + $("\pnpprov-Commissies.xml")))
$clientSidePages = $mainFile.Provisioning.Templates.ProvisioningTemplate.ClientSidePages
 
#remove pages to avoid duplicates 
$clientSidePages.RemoveChild($mainFile.Provisioning.Templates.ProvisioningTemplate.ClientSidePages.ClientSidePage)
 
foreach ( $page in $pagesList ) {
    #open page template xml
    $xmlContents = [xml][io.File]::ReadAllText($saveDir + "\" + $page)
    foreach ($node in $xmlContents.Provisioning.Templates.ProvisioningTemplate.ClientSidePages.ClientSidePage) {
			
        #copy nodes from page xml
        $importNode = $clientSidePages.OwnerDocument.ImportNode($node, $true);
        $clientSidePages.AppendChild($importNode) | Out-Null
		
        #save final tempate
        $mainFile.Save($($saveDir + $("\pnpprov-Commissies.xml")))
	
    }
}
 
popd`

**Comment by VesaJuvonen** [comment]
It's not PnP specific issue in first place, but yes - you can get the 500 exception in any out-of-the-box API call currently regardless if that's done through native APIs or PnP abstraction. This is being closely investigated currently.

**Comment by gabrielnovoa** [comment]
As @netti01 said, we identified a potential issue where several HTTP 500 errors are returned in calls made from SharePoint Online Client Side Object Model (_vti_bin/client.svc/ProcessQuery) solutions. If you have samples of failed responses (with SPRequestID) or Fiddler Traces, please open a support ticket on Office 365 Admin portal and refer this issue in GitHub for tracking.

**Comment by JBestebreurtje** [comment]
Any news?

**Comment by netti01** [comment]
This is the actual Service degradation incident appearing in Microsoft Admin Center. We assume that it is only visibel on tenants which raised the support request.

![image](https://user-images.githubusercontent.com/44964962/69221249-1932e100-0b77-11ea-8960-9e840a48b39c.png)

**Comment by koltyakov** [comment]
The description is not completely accurate. This is not only about admin or custom scripts, but any API calls including OOTB requests.

**Comment by VesaJuvonen** [comment]
This is still being actively worked on. This is not admin script specific issue. It seems to be specific to CSOM API usage though, which also PowerShell scripts use behind the scenes. That would explain the wrong conclusion around admin scripts in the above messaging... Any custom line-of-business application using CSOM APIs impacted.

If you are experiencing this, please open also support cases through the tenant admin support channels at the tenant admin UIs, so that the scale of impact is understood as that impacts on the prioritization of the investigations. Thanks everyone who have been already been active around this issue.

We will keep you up to date on the progress as there are any news.

**Comment by tarjeil** [comment]
In our tenant it is classified as an "Advisory" rather than an incident. Asked our Premier Support TAM to increase the severity..
![image](https://user-images.githubusercontent.com/21054534/69275421-a2303380-0bdc-11ea-9909-b8db3065b9f0.png)

**Comment by VesaJuvonen** [comment]
This issue is still being actively worked on. No ETA at this point.

Few things to notice:

- Issue is not script specific - any code using CSOM APIs can be impacted - this includes ISV/SI solutions or PowerShell scripts which use CSOM APIs (SPO or PnP PowerShell uses CSOM APIs under the covers)
- Please **keep on reporting the issue using Premier support or tenant admin support channels**, so that the scale of the issue is identified worldwide

We do apologize for the inconvenience and are actively working on resolving this. Thank you for your input around the issue.

**Comment by farid-ics** [comment]
Hello i have same isse with Apply-PnPProvisioningTemplate
"
Apply-PnPProvisioningTemplate : Le serveur distant a retourné une erreur : (500) Erreur interne du serveur.
Au caractère Ligne:3 : 1
+ Apply-PnPProvisioningTemplate -path "C:\Users\Administrateur\Document ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], WebException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

**Comment by bryqu** [comment]
Same issue for me. Frantically waiting for MS to resolve this!

**Comment by willemdeboer** [comment]
Same issue for me and our customers. Random 500 internal server errors are thrown during provisioning with CSOM. We create a modern teamsite and afterwards we start provisioning with CSOM. We don't even use PnP Provisioning, however we support that as an additional step, but since a couple of weeks the provisioning randomly fails while adding lists or content types or whatever to the site.

**Comment by advdberg** [comment]
Advisory is now upgraded to 'Incident' in admin center Service Health with following status report:

_Current status: We've identified a potential service update which may be the source of the impact. We're reviewing the specific configuration and code changes within the update to isolate the cause of the issue._

So fingers crossed it will be fixed and rolled-out before the weekend so we then have time to fix all failed provisioning jobs.

**Comment by VesaJuvonen** [comment]
This issue is still being actively worked on. No ETA at this point.

- Issue is not PnP or PowerShell Script specific - any code using CSOM APIs can be impacted - this includes ISV/SI solutions or PowerShell scripts which use CSOM APIs (SPO or PnP PowerShell uses CSOM APIs under the covers)
- Please keep on **reporting the issue using Premier support or tenant admin support channels**, so that the scale of the issue is identified worldwide

Thanks everyone who have already reported the issue from their environment as that helps to speed up the investigation process.

**Comment by jpalo** [comment]
Opened level A Premier ticket, not that I think they could help me specifically, but will update here if there's something new.

**Comment by cwdata** [comment]
We had these issues in our Web API using the SharePointOnline CSOM libraries. Upgrading to the latest stable version of PnP CSOM Extensions and the Microsoft CSOM library through Nuget seems to have fixed it. Maybe that'll work for others as well.

**Comment by jackpoz** [comment]
I'm getting the HTTP 500 using SharePointPnPCoreOnline NuGet package version 3.15.1911 on a demo tenant created from https://cdx.transform.microsoft.com/ (but it doesn't happen always)

**Comment by MikkoKoskinen** [comment]
Also, have a premier ticket open regarding this. We also did send some log files and PnP template just in case. Thank you for keeping us informed of the progress @VesaJuvonen . It helps us to communicate this to our clients or organization better. Not an ideal situation, but I'm sure you will find a solution.

**Comment by TOPDHI** [comment]
We're on latest NuGet SharePointPnPCoreOnline ver. 3.15.1911 and Microsoft.SharePointOnline.CSOM 16.1.19404.12000 and still having random issues @cwdata

**Comment by h3rd4** [comment]
> We're on latest NuGet SharePointPnPCoreOnline ver. 3.15.1911 and Microsoft.SharePointOnline.CSOM 16.1.19404.12000 and still having random issues @cwdata

issue is probably on the server side, CSOM version doesnt matter

**Comment by jpalo** [comment]
Issues are not related to package versions, no need to continue that discussion 😐

**Comment by SandeepVo** [comment]
Same issue with PnP and as well as CSOM API's

**Comment by SchauDK** [comment]
`Current status: We've isolated down the probable causes to a few changes that were recently made to the SharePoint Online service. We're continuing our investigation to confirm our findings and develop a mitigation plan.`

This definitely got worse starting a few days ago, however we started seeing this more than two months ago. Hence implemented our own retry logic within the OfficeDevPnP framework (ExecuteQueryRetry).

Maybe there's more to it than "a recent change". Maybe Microsoft can elaborate on what the recent change is??

**Comment by SchauDK** [comment]
> Issues are not related to package versions, no need to continue that discussion 😐
> 
> Premier ticket went as suspected, and we lowered the severity as it is already being investigated. Did send some of our error messages and they added our tenant to the list of affected tenants in the internal ticket of the issue.

If they want a list, I can add 100+ tenants!!!! ;-)

**Comment by MikkoKoskinen** [comment]
> This definitely got worse starting a few days ago, however we started seeing this more than two months ago.

I agree I've notice the same strange behavior in provisioning during the last two months also. I just wasn't sure where the error has been and retrying has been helped. Before at least.

**Comment by richardb52** [comment]
> `Current status: We've isolated down the probable causes to a few changes that were recently made to the SharePoint Online service. We're continuing our investigation to confirm our findings and develop a mitigation plan.`
> 
> This definitely got worse starting a few days ago, however we started seeing this more than two months ago. Hence implemented our own retry logic within the OfficeDevPnP framework (ExecuteQueryRetry).
> 
> Maybe there's more to it than "a recent change". Maybe Microsoft can elaborate on what the recent change is??

Agreed, we first hit this issue September 23rd. Definitely occurring a lot more now though.

**Comment by SandeepVo** [comment]
> This definitely got worse starting a few days ago, however we started seeing this more than two months ago. Hence implemented our own retry logic within the OfficeDevPnP framework (ExecuteQueryRetry).

I agree as well, We have been seeing this error since couple of months.
Was never able to reproduce when retried.

**Comment by SandeepVo** [comment]
Am i the only one feeling like this is just getting worse?

**Comment by DaniCorretja** [comment]
> Am i the only one feeling like this is just getting worse?

I feel you, bro =(

Would it help to open another ticket to Microsoft? I have the feeling they should have received hundreds because this is huge.

**Comment by VesaJuvonen** [comment]
Every single ticket has an impact. Please do not assume that your input or feedback would not have value for Microsoft as all of them do have direct influence on the following actions.

We are still actively working on this, but would absolutely ask **all people suffering on this issue to report it through Premier Support or standard tenant admin support channel** as each and every submission has an impact getting things resolved.

We do apologize for the inconvenience, but please do keep on reporting the issue if you are experiencing it. Thank you.

**Comment by VesaJuvonen** [comment]
Also - if any ISVs do have numerous tenants experiencing the issue, please do use the official channels to report that. Thank you.

**Comment by jeremyitprofessional** [comment]
Looks like it is more over the whole o365 platform, then only the sharepoint, yesterday there were 2 incidents in the health center.
Today only the one for office 365, but the problem is much wider then before

**Comment by AndyBolam** [comment]
Update - unfortunately when I run the PnP Provisioning via Azure Runbook in my client's tenant this is still failing.  Presume that this is an ongoing thing so will check again later today.

**Comment by VesaJuvonen** [comment]
Potential fix has been applied few hours ago, so we are curious on hearing the status also using this channel. Is the situation any better starting from now or not for your environments? 

Thank you for the status updates advance.

**Comment by SchauDK** [comment]
No change here.

![image](https://user-images.githubusercontent.com/13271356/69414104-60a1a480-0d12-11ea-85c9-b07e8523daee.png)

**Comment by jeremyitprofessional** [comment]
had this morning first time a get pnpprovisioningtemplate and apply successful, but second run was still error

**Comment by VesaJuvonen** [comment]
thx @SchauDK - let's follow up the situation for upcoming hours. It also might be that the fix has not yet been properly applied to your tenant, but it should be in progress. We are getting good messages from some customers, so looking positive for now.

**Comment by jpalo** [comment]
Seems to be working at least in one of our case with rather heavy API usage.

**Comment by ChrisOMetz** [comment]
@VesaJuvonen  - You mentioned that it might take some time before this fix will be applied to all tenants. Is there any option to check if this fix already applied to a specific tenant? Seams to work in one  of my tenants but for example not in any dev tenants

**Comment by VesaJuvonen** [comment]
@ChrisOMetz - unfortunately there's no way to check from tenant level if the fix is already applied. It should be worldwide deployed/enabled within next 4 hours which should remove then unnecessary 500's... You can still have exceptions, like 429's or 503's which are throttling related, but if your code is CSOM and using ExecuteQueryRetry method, it will automatically handle these situations.

**Comment by joelfmrodrigues** [comment]
Seems fine for us now 😃

**Comment by MikkoKoskinen** [comment]
In general, everything seems to be working for us. I still see some 500 errors, but our code was handling those situations anyway. I'll give it couple of more hours and retest.

**Comment by advdberg** [comment]
Started running some load tests on several 'internal' tenants, so far so good! Thanks for sharing the early status @VesaJuvonen, we will proceed with tests also on customer tenants.

**Comment by AndyBolam** [comment]
Am seeing 

Exception System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host 

in my Azure Runbooks (which are running PnP PowerShell scripts.  

Any chance this is the same issue?  Should I be logging this separately to the issue already known?

**Comment by VesaJuvonen** [comment]
@AndyBolam - does not look like a same issue in this case.

**Comment by SandeepVo** [comment]
> Am seeing
> 
> Exception System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host
> 
> in my Azure Runbooks (which are running PnP PowerShell scripts.
> 
> Any chance this is the same issue? Should I be logging this separately to the issue already known?

Wierd but I also have been seeing this issue on our tenant intermittently

**Comment by VesaJuvonen** [comment]
thx @SandeepVo  - This issue is around the 500 exception on the CSOM APIs, so let's not combine multiple different issues on single item. thx.

**Comment by SchauDK** [comment]
I guess the fix isn't globally deployed yet. I'll check again later.
![image](https://user-images.githubusercontent.com/13271356/69429755-96578500-0d34-11ea-81b6-c2d70d585c23.png)

**Comment by PhilThome** [comment]
It's better than yesterday, But we still encounter the error in about 50% of out provisioning trials.

**Comment by h3rd4** [comment]
For our dev and prod tenant is seems it works now. 3 provision requests within 1 hour and all has been processed successfully.

**Comment by TOPDHI** [comment]
In our tenant we believe that it is fixed. No 500 error since noon. Jupiiii.... Thank you @VesaJuvonen

**Comment by richardb52** [comment]
Looks to be resolved for us, thank you!

**Comment by frnk01** [comment]
@VesaJuvonen Good to hear it’s fixed but I wonder how a serious issue like this can run in production for over a week and Microsoft not noticing it without community feedback. Major lack of monitoring on the API?

**Comment by VesaJuvonen** [comment]
@frnk01  - Just to be clear here. Microsoft engineering did acknowledge and detected this issue in the background already, but as we started to have reports using multiple different social media channels and other forums, we wanted to also have public and open communications around this within this issue to provide more transparency and visibility on the progress of the issue.

This transparency helps all sides on the discussion and we also wanted to encourage people to use the normal support channels to report the issue as that's also the preferred option for any future issue. Obviously works was already being done on the background to address the root cause.

**Comment by VesaJuvonen** [comment]
Thanks everyone for your input around this issue and we do apologize the inconvenience potentially caused by this for you. As the root cause for this particular issue has been now addressed, will be closing this issue from here. We are working internally at Microsoft to minimize possibility of similar issues in the future.

If you have any other issues which seem similar, please do open a new issue in here and open a Premier Support case, where suitable.

**Comment by SchauDK** [comment]
@VesaJuvonen 
As this is considered solved, does that mean that we shouldn't see the error at all or should be see less?
I'm asking because we're still seeing it and I'm wondering how it will look on Monday when all our customers will start hitting SharePoint again.
![image](https://user-images.githubusercontent.com/13271356/69483753-8c647d80-0e2b-11ea-91fd-20dc86a2a016.png)

**Comment by jeremyitprofessional** [comment]
So it looks it was resolved last Saturday, in the evening i run some local scripts from different tenants and some azure function scripts. 
So seems to be over.

**Comment by SchauDK** [comment]
It's not over! We have 53 occurrences within the last hour.

![image](https://user-images.githubusercontent.com/13271356/69526729-241cb580-0f6b-11ea-84c6-6cf0ab642da8.png)

**Comment by PhilThome** [comment]
1 of 4 provisionings still showed this error this morning.

**Comment by h3rd4** [comment]
Error started to appear again.
Todays morning provision request showed this error. 
:(

**Comment by AndyBolam** [comment]
Yep same here.  Was ok Friday and Saturday.  Now clients are seeing this again today.
Can this be reopened please?!  It's clearly not resolved.

**Comment by advdberg** [comment]
Same here on several tenants. Was working fine since friday afternoon (CET) @VesaJuvonen @jansenbe @gabrielnovoa do you still advise to create new service requests?

**Comment by robinmeure** [comment]
Can someone also post the body of the 500 error being returned? E.g. is it the same as before (nullref?)

**Comment by AndyBolam** [comment]
Hi,

Getting this during provisioning via Azure Runbook.  Same Error:

**"Error occured: The remote server returned an error: (500) Internal Server Error."**

**Comment by advdberg** [comment]
Here's a StackTrace: 

at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.SharePoint.Client.SPWebRequestExecutor.<ExecuteAsync>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext() --- End of stack trace from previous location where exception was thrown --- at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay, String userAgent) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectField.UpdateField(Web web, String fieldId, XElement templateFieldElement, PnPMonitoredScope scope, TokenParser parser, String originalFieldXml) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectField.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation) at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo, Boolean calledFromHierarchy, TokenParser tokenParser) at CallSite.Target(Closure , CallSite , Object , Object , Object , Object )

**Comment by robinmeure** [comment]
Thanks for the stacktrace, but we actually need the headers and the body of the response

**Comment by VesaJuvonen** [comment]
If anyone is suffering from this again, please reopen the issue with the Premier or standard support, so that we get things again moving. 

We confirmed that in global level the 500 issue was gone last week, but apparently situation has been changed and we'll need to investigate the updated reports around this to understand what happened.

Will provide an update when we have something to share externally.

**Comment by advdberg** [comment]
@robinmeure is this helpful?

```
HTTP/1.1 500 Internal Server Error
Content-Length: 53
P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
SPRequestGuid: 3d481b9f-00b8-a000-5a62-e46a8e113f6a
request-id: 3d481b9f-00b8-a000-5a62-e46a8e113f6a
MS-CV: nxtIPbgAAKBaYuRqjhE/ag.0
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
X-Powered-By: ASP.NET
MicrosoftSharePointTeamServices: 16.0.0.19506
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
X-MSEdge-Ref: Ref A: 5B0418DF0AAF41C6895E252F1B2287DE Ref B: AMS04EDGE0822 Ref C: 2019-11-25T11:34:01Z
Date: Mon, 25 Nov 2019 11:34:01 GMT

Object reference not set to an instance of an object.
```

**Comment by robinmeure** [comment]
> @robinmeure is this helpful?
> 
> ```
> HTTP/1.1 500 Internal Server Error
> Content-Length: 53
> P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
> SPRequestGuid: 3d481b9f-00b8-a000-5a62-e46a8e113f6a
> request-id: 3d481b9f-00b8-a000-5a62-e46a8e113f6a
> MS-CV: nxtIPbgAAKBaYuRqjhE/ag.0
> Strict-Transport-Security: max-age=31536000
> X-FRAME-OPTIONS: SAMEORIGIN
> X-Powered-By: ASP.NET
> MicrosoftSharePointTeamServices: 16.0.0.19506
> X-Content-Type-Options: nosniff
> X-MS-InvokeApp: 1; RequireReadOnly
> X-MSEdge-Ref: Ref A: 5B0418DF0AAF41C6895E252F1B2287DE Ref B: AMS04EDGE0822 Ref C: 2019-11-25T11:34:01Z
> Date: Mon, 25 Nov 2019 11:34:01 GMT
> 
> Object reference not set to an instance of an object.
> ```

Yep! That's we need :) Are you able to raise a support ticket?

**Comment by advdberg** [comment]
@robinmeure I'll ask our customer to re-open/create a ticket as this message is from their tenant and we're only an ISV delivering provisioning tooling

**Comment by PhilThome** [comment]
Same here. I've opened an tenant admin support case, and asked out customer to create a premier support ticket.

**Comment by SachinRanka** [comment]
We have a ticket for this as well.

**Comment by tarjeil** [comment]
We also registered a (new) premier case..

**Comment by MikkoKoskinen** [comment]
I just re-opened our premier case. Started to see the same errors again for today.

**Comment by jeremyitprofessional** [comment]
Are there still problems?

**Comment by SchauDK** [comment]
For the first time since two months ago, we haven't seen this for 3 days now.
On the other hand performance is extremely bad. So don't know what is worse.

We'll keep monitoring.

**Comment by lianakorek** [comment]
Hello - 

What we are experiencing would fall under this issue title, but differs slightly from the original issue reported.  

We have a process that uses a SharePoint REST API to run a Folder Query to determine if a relative folder already exists within a Document Library.  If the folder exists, the process saves the document to the existing folder.  If the folder does not exist, the process creates a new folder and saves the document to the newly created folder. (see Figure 1)

In the screenshot below (see Figure 2), you'll see 2 document libraries within the same site.  The Folder Query and subsequent adding to existing or creating new folder works just fine for the Account folder.  The process for the commission folder fails at the Folder Query with message "500 Internal Server Error".

This is the endpoint of the request:
GET /sites/CompanySite/_api/web/GetFolderByServerRelativeUrl('commission')/Folders?$select=Files,ServerRelativeUrl&o$select=Files,ServerRelativeUrl&$expand=Files

Important to make note that this is not the first time this has happened.  The timeline seems to coincide with others in this thread.  _The data below is in reference to the commission Folder Query only, the Account Folder Query has never failed_.  Also, the calls are triggered by specific user actions, so the issue or resolution could have taken place anytime within the last success/last failure window.

**1st "500 Internal Server Error" occurrence:**  10/10/19.  Last successful Folder Query at 5:38pm EST.  First failed Folder Query at 6:00pm EST.  Every single call from this point forward failed until ....

**Resolved magically (Folder Query and subsequent process successful, no longer receiving "500 Internal Server Error"):**  11/4/19.  Last failed Folder Query at 5:49pm EST.  First successful Folder Query at 7:13pm.

**2nd "500 Internal Server Error" occurrence:** 11/29/19.  Last successful Folder Query at 5:24pm EST on 11/29/19.  First failed Folder Query at 8:00pm EST on 11/30/19.  Every single call is still failing now.

![2019-12-03_15-31-31](https://user-images.githubusercontent.com/36540870/70087472-633dad00-15e2-11ea-9354-60003361b1c7.png)
![2019-12-03_13-58-43](https://user-images.githubusercontent.com/36540870/70087478-66389d80-15e2-11ea-92be-f86d0dfdedd5.png)

**Comment by jeremyitprofessional** [comment]
At the moment when we try to create new sites with an API, but also just with pnp powershell or even with spo powershell create a normal teamsite sitecollection without an unifiedgroup it takes for ever to complete

**Comment by advdberg** [comment]
In some tenants we see an increasing number of '(503) Server Unavailable' and 'unable to connect to the remote server' error messages, I'm not sure it's related to the internal server errors but it occurs in the same commands.

@VesaJuvonen I guess you would like us to create new service requests for these? Would a separate issue in the issue list be helpful? I saw it's also mentioned in the comments of issue #4744 around throttling...

**Comment by robinmeure** [comment]
Hey Ad, yes, since of the beginning of this week we are seeing 503's. This is communicated in the message centers of affected tenants and the PG is well aware of this issue and is working on a fix.

________________________________

**Comment by AndyBolam** [comment]
Is there any idea of when this issue will be resolved?  It would seem that where we were seeing 500, we now see 503?

**Comment by robinmeure** [comment]
> Is there any idea of when this issue will be resolved? It would seem that where we were seeing 500, we now see 503?

Every week a different 500 error! :)
J/k, please log a ticket with the correlation id's with support.

**Comment by andrewconnell** [comment]
_I'm going to attempt to wrap this issue up after a discussion with SharePoint engineering & getting some guidance from them..._

Unfortunately, this is not something that can effectively be addressed in this forum. As this [wiki page](https://github.com/SharePoint/sp-dev-docs/wiki/Issue-List#what-belongs-in-this-issue-list) explains in two sections _"What belongs on this issue list"_ & _"What doesn't belong in the issue list"_, this sp-dev-docs issue list is for SharePoint development issues. If there is a product issue, Microsoft/SharePoint support doesn't engage here.

**Put simply: these issues aren't support tickets... if there's a product/service issue, you need to open a ticket. If you're in SharePoint Online, you can do that from the Microsoft 365 Portal / SharePoint Admin Center.**

Please refer to these two comments as replies with guidance from Microsoft:
- https://github.com/SharePoint/sp-dev-docs/issues/4924#issuecomment-558107240
- https://github.com/SharePoint/sp-dev-docs/issues/5392#issuecomment-601665396

**If you are getting 429's**, those are throttling issues and the service is working by design as you are submitting too many requests that are now being throttled. Please refer to [this page](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online) and [this page](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/handle-sharepoint-online-throttling-by-using-exponential-back-off) in the docs for more details on throttling. You will need to modify your solution to address this... these are not "errors" in the service.

**If you are getting 500's or 503's**, these are considered _product issues_. These status codes mean there is a problem with the service. [500 is internal server error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500) & [503 is service unavailable](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503). There's nothing we in the community can do here to investigate nor are the MSFT folks in the extensibility areas (SPFx/APIs/etc) who frequent this list can do. Microsoft support has to engage.

Before opening a ticket, follow the process of elimination. Make sure it's not the tool/library you're using (including PnP libraries, cmdlets, etc). If you get a 50X error code when using a PnP library or cmdlet, but not when you use the REST API, then that points more to a problem with the library & not with the endpoint. In that case, it would make sense to post an issue to the appropriate repo's issue list for that library / project.

When opening your ticket, the more detail you can provide (correlation ID's, request ID's) and more "pure SharePoint" you can show in your problem (test the underlying endpoints... exclude things like PnP libraries, cmdlets, tools, etc) as that shows it is a SharePoint issue, not a possible issue with one of the layers between what you are doing and SharePoint. It's the classic process of elimination.

I hope this helps... I suspect some will be frustrated with this answer. However, as it stands this issue would just sit out there. with no resolution like others.
