### ISSUE TITLE
While adding new file in folder getting"File Not Found." exception

### ISSUE THREAD

**Issue by PranavJoshi1070** [SharePoint/sp-dev-docs#4944]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

I am working on SharePoint Online custom webpart in classic SharePoint page. I am trying to add a video file (.mp4) to a document library using REST API. I am following the code example given in Microsoft documentation (Link given below).

https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/upload-a-file-by-using-the-rest-api-and-jquery

But the AJAX call to add file in a folder returns a 404 File not found exception:

{"error":{"code":"-2147024894, System.IO.FileNotFoundException","message":{"lang":"en-US","value":"File Not Found."}}}

Strangely, the video file with a folder is created properly but still it returns a 404 error. I am confused that on creation of files successfully why it gives error. 
Can anyone please help identify the issue? Really appreciated. 

My Code is given below:

`	function StartFileUploadingProcess()
	{
		var getFile = getFileBuffer();
		getFile.done(function (arrayBuffer) {
			console.log('buffer is created');
			var addFile = addFileToFolder(arrayBuffer);
			addFile.done(function (file, status, xhr) {	
				var getItem = getListItem(file.d.ListItemAllFields.__deferred.uri);
				getItem.done(function (listItem, status, xhr) {
					fileUploadedInfo.push({ID:listItem.d.Id, FileName:file.d.Name, Category:imageType});
					deferred1.resolve(fileUploadedInfo);
					var changeItem = updateListItemCategory(listItem.d.__metadata, imageType);
					changeItem.done(function (data, status, xhr) {
						console.log('successfully changed category to: ' +imageType);																						
					});
					changeItem.fail(UpdateListItem(listItem, imageType));												
				})
				getItem.fail(onError1);
			});
			addFile.fail(onError2);
		});
		getFile.fail(onError3);
	}
	
	function UpdateListItem(listItem, imageType)
	{		
		// Code to update list item
	}    
		
	function getFileBuffer() {
		var deferred = jQuery.Deferred();
		var reader = new FileReader();
		reader.onloadend = function (e) {
			deferred.resolve(e.target.result);
		}
		reader.onerror = function (e) {
			deferred.reject(e.target.error);
		}
		reader.readAsArrayBuffer(fileObject.files[fileIndex]);
		return deferred.promise();
	}
	
	// Add the file to the file collection in the Shared Documents folder.
	function addFileToFolder(arrayBuffer) {	
		var fileCollectionEndpoint = String.format("{0}/_api/web/getfolderbyserverrelativeurl('{1}')/files" + "/add(url='{2}',overwrite=true)", serverUrl, serverRelativeUrlToFolder, fileName);
		// Send the request and return the response.
		// This call returns the SharePoint file.		
		return jQuery.ajax({
			url: fileCollectionEndpoint,
			type: "POST",
			data: arrayBuffer,
			processData: false,
			headers: {
                "accept": "application/json;odata=verbose",
                'content-type':'application/json;odata=verbose',
                "X-RequestDigest": jQuery("#__REQUESTDIGEST").val(),
                "content-length": arrayBuffer.byteLength
            }
		});		
	}
	
	// Get the list item that corresponds to the file by calling the file's ListItemAllFields property.
	function getListItem(fileListItemUri) {		
		// Send the request and return the response.
		if(fileListItemUri.length>0)
		return jQuery.ajax({
			url: fileListItemUri,
			type: "GET",
			headers: { "accept": "application/json;odata=verbose" }			
		});
		else
		return null;
	}
	
	// Change the display name and title of the list item.
	function updateListItemCategory(itemMetadata, categoryType) {

		// Define the list item changes. Use the FileLeafRef property to change the display name. 
		// For simplicity, also use the name as the title. 
		// The example gets the list item type from the item's metadata, but you can also get it from the
		// ListItemEntityTypeFullName property of the list.
		var body;
		if(categoryType.toLowerCase()!='video')
			body = String.format("{{'__metadata':{{'type':'{0}'}},'Category':'{1}','Title':'{2}'}}", itemMetadata.type, categoryType, fileName);
		else
			body = String.format("{{'__metadata':{{'type':'{0}'}},'Title':'{1}'}}", itemMetadata.type, fileName);	
		//var body = String.format("{{'__metadata':{{'type':'{0}'}},'Category':'{1}'}}", itemMetadata.type, categoryType);
		// console.log('itemMetadata.uri ->'+itemMetadata.uri);
		// Send the request and return the promise.
		// This call does not return response content from the server.
		return jQuery.ajax({
			url: itemMetadata.uri,
			type: "POST",
			data: body,
			timeout:500,
			headers: {
				"X-RequestDigest": jQuery("#__REQUESTDIGEST").val(),
				"content-type": "application/json;odata=verbose",
				"content-length": body.length,
				"IF-MATCH": "*",
				"X-HTTP-Method": "MERGE"
			}
		});
	}
	
	function onError1(error){
		console.log(error.responseText);
	}
	
	function onError2(error){
		console.log(error.responseText);

	}

	function onError3(error){
		console.log(error.responseText);

	}
	
	// Display error messages. 
	function onError(error) {
		alert(error.responseText);
		/*if(uploadTried<5){
				$scope.Search(imageType);
				$scope.UploadImages();
				uploadTried++;
			}
		var result;
		var r = confirm("Error while uploading the image. For re-try, please click OK.");
		if (r == true) {			    
							
		} else {
			uploadTried=0;
			$("#processing").attr("src", "");
		}*/		    	
	}	
	return deferred1.promise();
}`

**Comment by OS-Lee** [comment]
If your site url like https://tenant.sharepoint.com/sites/lee, the server relative url looks like ` var serverRelativeUrlToFolder = '/sites/lee/MyDoc/SubFolder'`

I tested the script in my online environment, it's working fine.

![image](https://user-images.githubusercontent.com/40845109/69610388-ab9b1f00-1066-11ea-8845-cbe21f0ecc67.png)


`<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.9.1.min.js" type="text/javascript"></script>
    <input id="getFile" type="file" /><br />
    <input id="displayName" type="text" value="Enter a unique name" /><br />
    <input id="addFileButton" type="button" value="Upload" onclick="uploadFile()" />

    <script type="text/javascript">
        'use strict';

        jQuery(document).ready(function () {

            // Check for FileReader API (HTML5) support.
            if (!window.FileReader) {
                alert('This browser does not support the FileReader API.');
            }
        });

        // Upload the file.
        // You can upload files up to 2 GB with the REST API.
        function uploadFile() {

            // Define the folder path for this example.
            var serverRelativeUrlToFolder = '/sites/lee/MyDoc/SubFolder';

            // Get test values from the file input and text input page controls.
            var fileInput = jQuery('#getFile');
            var newName = jQuery('#displayName').val();

            // Get the server URL.
            var serverUrl = _spPageContextInfo.webAbsoluteUrl;

            // Initiate method calls using jQuery promises.
            // Get the local file as an array buffer.
            var getFile = getFileBuffer();
            getFile.done(function (arrayBuffer) {

                // Add the file to the SharePoint folder.
                var addFile = addFileToFolder(arrayBuffer);
                addFile.done(function (file, status, xhr) {

                    // Get the list item that corresponds to the uploaded file.
                    var getItem = getListItem(file.d.ListItemAllFields.__deferred.uri);
                    getItem.done(function (listItem, status, xhr) {

                        // Change the display name and title of the list item.
                        var changeItem = updateListItem(listItem.d.__metadata);
                        changeItem.done(function (data, status, xhr) {
                            alert('file uploaded and updated');
                        });
                        changeItem.fail(onError);
                    });
                    getItem.fail(onError);
                });
                addFile.fail(onError);
            });
            getFile.fail(onError);

            // Get the local file as an array buffer.
            function getFileBuffer() {
                var deferred = jQuery.Deferred();
                var reader = new FileReader();
                reader.onloadend = function (e) {
                    deferred.resolve(e.target.result);
                }
                reader.onerror = function (e) {
                    deferred.reject(e.target.error);
                }
                reader.readAsArrayBuffer(fileInput[0].files[0]);
                return deferred.promise();
            }

            // Add the file to the file collection in the Shared Documents folder.
            function addFileToFolder(arrayBuffer) {

                // Get the file name from the file input control on the page.
                var parts = fileInput[0].value.split('\\');
                var fileName = parts[parts.length - 1];

                // Construct the endpoint.
                var fileCollectionEndpoint = String.format(
                    "{0}/_api/web/getfolderbyserverrelativeurl('{1}')/files" +
                    "/add(overwrite=true, url='{2}')",
                    serverUrl, serverRelativeUrlToFolder, fileName);

                // Send the request and return the response.
                // This call returns the SharePoint file.
                return jQuery.ajax({
                    url: fileCollectionEndpoint,
                    type: "POST",
                    data: arrayBuffer,
                    processData: false,
                    headers: {
                        "accept": "application/json;odata=verbose",
                        "X-RequestDigest": jQuery("#__REQUESTDIGEST").val(),
                        "content-length": arrayBuffer.byteLength
                    }
                });
            }

            // Get the list item that corresponds to the file by calling the file's ListItemAllFields property.
            function getListItem(fileListItemUri) {

                // Send the request and return the response.
                return jQuery.ajax({
                    url: fileListItemUri,
                    type: "GET",
                    headers: { "accept": "application/json;odata=verbose" }
                });
            }

            // Change the display name and title of the list item.
            function updateListItem(itemMetadata) {

                // Define the list item changes. Use the FileLeafRef property to change the display name.
                // For simplicity, also use the name as the title.
                // The example gets the list item type from the item's metadata, but you can also get it from the
                // ListItemEntityTypeFullName property of the list.
                var body = String.format("{{'__metadata':{{'type':'{0}'}},'FileLeafRef':'{1}','Title':'{2}'}}",
                    itemMetadata.type, newName, newName);

                // Send the request and return the promise.
                // This call does not return response content from the server.
                return jQuery.ajax({
                    url: itemMetadata.uri,
                    type: "POST",
                    data: body,
                    headers: {
                        "X-RequestDigest": jQuery("#__REQUESTDIGEST").val(),
                        "content-type": "application/json;odata=verbose",
                        "content-length": body.length,
                        "IF-MATCH": itemMetadata.etag,
                        "X-HTTP-Method": "MERGE"
                    }
                });
            }
        }

        // Display error messages.
        function onError(error) {
            alert(error.responseText);
        }
    </script>`

**Comment by PranavJoshi1070** [comment]
Thank you @OS-Lee for your solution. I tried it on the "Shared Document" library and it uploads the document as expected. I updated the code to create a folder first and add file into it.
HOWEVER, when I try the code in another document library "DocLibrary2" the code fails to upload the video. 
I tried comparing the 'Shared Document' and 'DocLibrary2'. The second doc library has following additional setting. Not sure if this setting is preventing from uploading the video file. 

![image](https://user-images.githubusercontent.com/57978307/69864472-fd40e500-12c4-11ea-94d0-a9152d739946.png)


My updated code:

`<html>  
  
    <head>  
        <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.9.1.min.js" type="text/javascript"></script> 
        <script language="javascript" type="text/javascript">  
        'use strict';

    jQuery(document).ready(function () {

        // Check for FileReader API (HTML5) support.
        if (!window.FileReader) {
            alert('This browser does not support the FileReader API.');
        }
    });

    // Upload the file.
    // You can upload files up to 2 GB with the REST API.
    function uploadFile() {

        // Define the folder path for this example.
        var serverRelativeUrlToFolder = '';

        // Get test values from the file input and text input page controls.
        var fileInput = jQuery('#getFile');
        var newName = jQuery('#displayName').val();
        var folderName = fileInput[0].files[0].name.split('.mp4')[0]
	
        // Get the server URL.
        var serverUrl = _spPageContextInfo.webAbsoluteUrl;
		var addFolder = createFolder();
		addFolder.done(function(data, status, xhr){
		console.log("FOLDER CREATED!!");
		serverRelativeUrlToFolder = '/<path of of my site>/Shared%20Documents/'+data.d.Name;
			// Initiate method calls using jQuery promises.
	        // Get the local file as an array buffer.
	        var getFile = getFileBuffer();
	        getFile.done(function (arrayBuffer) {
	
	            // Add the file to the SharePoint folder.
	            var addFile = addFileToFolder(arrayBuffer);
	            addFile.done(function (file, status, xhr) {
	
	                // Get the list item that corresponds to the uploaded file.
	                var getItem = getListItem(file.d.ListItemAllFields.__deferred.uri);
	                getItem.done(function (listItem, status, xhr) {
	
	                    // Change the display name and title of the list item.
	                    var changeItem = updateListItem(listItem.d.__metadata);
	                    changeItem.done(function (data, status, xhr) {
	                        alert('file uploaded and updated');
	                    });
	                    changeItem.fail(onError);
	                });
	                getItem.fail(onError);
	            });
	            addFile.fail(onError);
	        });
	        getFile.fail(onError);		
        });
		addFolder.fail(onError);

        // Get the local file as an array buffer.
        function getFileBuffer() {
            var deferred = jQuery.Deferred();
            var reader = new FileReader();
            reader.onloadend = function (e) {
                deferred.resolve(e.target.result);
            }
            reader.onerror = function (e) {
                deferred.reject(e.target.error);
            }
            reader.readAsArrayBuffer(fileInput[0].files[0]);
            return deferred.promise();
        }
        
        function createFolder(){
	        var fileCollectionEndpoint = serverUrl + "/_api/Web/Folders/add('Shared%20Documents/"+ folderName+"')";
        	
            // Send the request and return the response.
            // This call returns the Folder.
            return jQuery.ajax({
                url: fileCollectionEndpoint,
                type: "POST",
               	headers: {
                    "accept": "application/json;odata=verbose",
                    "content-type"    : "application/json; odata=verbose",
                    "X-RequestDigest": jQuery("#__REQUESTDIGEST").val(),
                }
            });
        }

        // Add the file to the file collection in the Shared Documents folder.
        function addFileToFolder(arrayBuffer) {

            // Get the file name from the file input control on the page.
            var parts = fileInput[0].value.split('\\');
            var fileName = parts[parts.length - 1];

            // Construct the endpoint.
            var fileCollectionEndpoint = String.format(
                "{0}/_api/web/getfolderbyserverrelativeurl('{1}')/files" +
                "/add(overwrite=true, url='{2}')",
                serverUrl, serverRelativeUrlToFolder, fileName);

            // Send the request and return the response.
            // This call returns the SharePoint file.
            return jQuery.ajax({
                url: fileCollectionEndpoint,
                type: "POST",
                data: arrayBuffer,
                processData: false,
                headers: {
                    "accept": "application/json;odata=verbose",
                    "X-RequestDigest": jQuery("#__REQUESTDIGEST").val(),
                    "content-length": arrayBuffer.byteLength
                }
            });
        }

        // Get the list item that corresponds to the file by calling the file's ListItemAllFields property.
        function getListItem(fileListItemUri) {

            // Send the request and return the response.
            return jQuery.ajax({
                url: fileListItemUri,
                type: "GET",
                headers: { "accept": "application/json;odata=verbose" }
            });
        }

        // Change the display name and title of the list item.
        function updateListItem(itemMetadata) {

            // Define the list item changes. Use the FileLeafRef property to change the display name.
            // For simplicity, also use the name as the title.
            // The example gets the list item type from the item's metadata, but you can also get it from the
            // ListItemEntityTypeFullName property of the list.
            var body = String.format("{{'__metadata':{{'type':'{0}'}},'FileLeafRef':'{1}','Title':'{2}'}}",
                itemMetadata.type, newName, newName);

            // Send the request and return the promise.
            // This call does not return response content from the server.
            return jQuery.ajax({
                url: itemMetadata.uri,
                type: "POST",
                data: body,
                headers: {
                    "X-RequestDigest": jQuery("#__REQUESTDIGEST").val(),
                    "content-type": "application/json;odata=verbose",
                    "content-length": body.length,
                    "IF-MATCH": itemMetadata.etag,
                    "X-HTTP-Method": "MERGE"
                }
            });
        }
    }

    // Display error messages.
    function onError(error) {
        alert(error.responseText);
    }
        </script>  
    </head>  
  
    <body>  
        <input id="getFile" type="file"><br> <input id="btnUploadFiles" type="button" value="Upload2" onclick="uploadFile()">  
    </body>  
    </html>  `

**Comment by andrewconnell** [comment]
I still see references to the `Shared%20Documents` library in your updated code...
