### ISSUE TITLE
SPFx WebPart on appagehost.aspx will be removed after a few seconds

### ISSUE THREAD

**Issue by db3005** [SharePoint/sp-dev-docs#5012]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

We have created a WebPart to render as an application page, so we leave the supportedHosts in the manifest.json empty and use the apppagehost.aspx URL to render our WebPart. The url looks like this: {siteUrl}/_layouts/15/appPageHost.aspx?componentId={componentId}.

#### Observed Behavior

This method worked well for a long time, now we have a problem with our first release tenant, where the WebPart is removed after a few seconds.

#### Steps to Reproduce

Create a new WebPart with SPFx version 1.8.2 and use the apppagehost.aspx page to render your WebPart. Our tenant is running in the first release mode, it seems like that the other tenants are not affected. 

Open the URL and the WebPart will be rendered:

![image](https://user-images.githubusercontent.com/32265743/70608279-25531100-1c00-11ea-8a25-29b767df7836.png)

After a few seconds:

![image](https://user-images.githubusercontent.com/32265743/70608301-300da600-1c00-11ea-9600-0e3d7ae0fe74.png)

Html here looks like there should be a loading spinner...

![image](https://user-images.githubusercontent.com/32265743/70608520-8f6bb600-1c00-11ea-8059-82f447045188.png)

I debuged a little bit in the SharePoint js files and found a file https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_6c1243ef07241a9f41fe54d8c7adbc98.js which probably causes the issue. In this script  a _clearChildren function is called that removes the content of the web part.

![image](https://user-images.githubusercontent.com/32265743/70607055-0d7a8d80-1bfe-11ea-8bd1-9f7b9eb2a072.png)

Any Suggestions what we could do to make it work again?

**Comment by andrewconnell** [comment]
Unless I'm mistaken, what you're doing isn't a supported scenario. That page is used to host components as tabs in Microsoft Teams. MSFT may have added logic to clear the page if a Teams context isn't detected to remove it from the page.

You may try using the current version of SPFx 1.9.1, but pretty sure this scenario isn't supported. The other option would be to set it as a full page app page to see if that works for your scenario.

**Comment by db3005** [comment]
Hmm I think that for the teams tabs teamshostedapp.aspx is used. In the SPFx 1.8 release notes MSFT announced that there is a static page under appPageHost.aspx that will host any component in an app page - https://github.com/SharePoint/sp-dev-docs/wiki/SharePoint-Framework-v1.8-release-notes#app-pages - We have been using this page for almost half a year and it has always worked very well.

If we set it as a full page app page, do we need to add a page to each site collection to have this app page avaiable? That was the big advantage from the apppagehost.aspx, which is already on every site and we can simply render our component there.

**Comment by patmill** [comment]
@db3005 - correct.  This should be supported, and you don't need to create a one-off app page .aspx in the sitepages library per site.  As to why the spinner clearing is removing it - that sounds like a bug.

Are you by any chance doing rendering inside your onInit function (or in a promise resolved by your onInit function)?

**Comment by db3005** [comment]
@patmill - No, I start my rendering only in the render function. Even if I render a single div, it will be removed after 4-6 seconds.

![image](https://user-images.githubusercontent.com/32265743/70787479-06cf5000-1d8f-11ea-80d7-e200a47370bf.png)
->
![image](https://user-images.githubusercontent.com/32265743/70787490-0e8ef480-1d8f-11ea-8027-21985f044d7e.png)

**Comment by OverkillTV** [comment]
Could it relate to the webpart properties panel ? In my issue #5019 I found out that I can't view the properties panel after those webparts disappeared.
If I click on normal ootb webparts they show properties panel just fine, and if I click back on my custom webpart it will still show the properties panel but after I save the page and refresh, the properties panel cannot be opened again and the wp will disappear from the page.

**Comment by db3005** [comment]
@patmill @andrewconnell - Any updates on this issue?

**Comment by MrTantum** [comment]
@patmill Any updates on this? This problem has reached our productive tenants.

We created a ticket yesterday and the support engineer told us that this topic is being worked on but he could not give and eta or an internal id for this problem.

**Comment by kemesfun** [comment]
This issue has been fixed and will be part of the next prod rollout.

**Comment by andrewconnell** [comment]
@kemesfun The accepted practice in this repo is to leave issues open until the fix is actually implemented & confirmed resolved by the OP (/cc @VesaJuvonen)

**Comment by MrTantum** [comment]
Has the prod rollout already happened? We just retested this and is still not working.

**Comment by kemesfun** [comment]
@MrTantum Can you give more details of which release tenant you are on. I am getting an error now, but it is related to preloaded information on page and not with the webpart.

**Comment by MrTantum** [comment]
It is a pre-release tenant:

![image](https://user-images.githubusercontent.com/31658807/77731961-38012280-7004-11ea-896b-71681100ca36.png)

Tenant ID is: b92496b8-2082-44c9-8996-26a1d0e8e3f8

**Comment by OverkillTV** [comment]
This is happening in my production. Not sure if relating to this but my custom web part disappear right after added to the page.

I recorded the screen for more defails: https://youtu.be/-2UWAyXuZTY

**Comment by kemesfun** [comment]
@OverkillTV I couldn't repro this issue using a prod tenant. 

The issue that I get is 'TypeError: Cannot read property 'Content' of undefined'. This is a new issue and isn't related to the original issue

**Comment by andrewconnell** [comment]
@db3005 can you confirm the issue has been resolved? MSFT (@kemesfun) [stated the fix has been applied and rolledout](https://github.com/SharePoint/sp-dev-docs/issues/5012#issuecomment-589806029).

**Comment by db3005** [comment]
@andrewconnell No, unfortunately the error still occurs. I created another standard SPFx WebPart without any changes and recorded the screen:

![screen-capture](https://user-images.githubusercontent.com/32265743/78028096-bd673880-735e-11ea-974f-a76bd96a72b1.gif)

**Comment by OverkillTV** [comment]
> @OverkillTV I couldn't repro this issue using a prod tenant.
> 
> The issue that I get is 'TypeError: Cannot read property 'Content' of undefined'. This is a new issue and isn't related to the original issue

Yeah I have 2 prod tenants. One has this issue, the other doesn't so not really sure why. They are in standard release.

**Comment by kemesfun** [comment]
@db3005  can you do the following commands: ctrl-shift-f12. I want to see which version of sp-client you are using because it is likely that the farm that you are didn't receive the code changes that were made that resolved this issue.
@OverkillTV  It could be that your prod tenants are on two separate farms, so one has the newer code and the other doesn't. Can you confirm this?

**Comment by db3005** [comment]
@kemesfun here's the screenshot:

![image](https://user-images.githubusercontent.com/32265743/78100888-23e36980-73e6-11ea-87ba-2e17888915f5.png)

Is that enough for you to see the version?

**Comment by OverkillTV** [comment]
> @db3005 can you do the following commands: ctrl-shift-f12. I want to see which version of sp-client you are using because it is likely that the farm that you are didn't receive the code changes that were made that resolved this issue.
> @OverkillTV It could be that your prod tenants are on two separate farms, so one has the newer code and the other doesn't. Can you confirm this?

Yeah they are in different farms. But not sure how to check if one has newer than the other.

**Comment by kemesfun** [comment]
@db3005  sorry I forgot to ask you to click performance, you should see client version.
@OverkillTV  running the command: ctrl-shift-f12, then clicking performance should show which version of sp-client you are on. This can verify that one farm has the newer code than the other.

**Comment by OverkillTV** [comment]
@kemesfun : They are in different version as well. Here is the screenshot:
Issued one:
![issuedTenant](https://user-images.githubusercontent.com/24540444/78215958-cce1a100-7486-11ea-9c8d-ff6040048d95.jpg)

No issue one:
![NoNissuedTenant](https://user-images.githubusercontent.com/24540444/78215975-d2d78200-7486-11ea-8eb4-7431b2bdfe3f.jpg)

**Comment by db3005** [comment]
@kemesfun For me it is exactly the opposite, version sp-client-prod_2020-03-13.002 causes the issue

![image](https://user-images.githubusercontent.com/32265743/78216302-d20c1380-74b9-11ea-8465-ca9ed1d62487.png)

**Comment by kemesfun** [comment]
@db3005 @OverkillTV  The reason for this can be because a Flight is on. Can you search for the method  _renderWebPartOld? If this doesn't exist then the Flight is on.

**Comment by OverkillTV** [comment]
undefined in console or am I suppose to search in any specific files ?

**Comment by kemesfun** [comment]
@OverkillTV  ctrl+shit+f and search for the file that has this. If it doesn't show, then the Flight is on.

**Comment by OverkillTV** [comment]
There is file that contains the _renderWebPartOld
![SearchRS](https://user-images.githubusercontent.com/24540444/78282530-7017d200-74ea-11ea-8e13-ac9e83b1c654.jpg)

**Comment by kemesfun** [comment]
@OverkillTV can you add a breakpoint on that method, it shouldn't hit it since that was the part that was causing the webpart disappearing. It should hit _renderWebPart.

**Comment by OverkillTV** [comment]
> @OverkillTV can you add a breakpoint on that method, it shouldn't hit it since that was the part that was causing the webpart disappearing. It should hit _renderWebPart.

The script file is too big for my chrome so it hung up.
So I used Google Chrome Canary instead to step in and surprisingly the _renderWebPartOld doesn't show up in any files when I search. I tried with _renderWebPart and it indeed hit the _renderWebPart line of code.

**Comment by kemesfun** [comment]
@OverkillTV  This means that your tenant doesn't have the fix for this issue. The _renderWebPartOld indicates that the older logic from _renderWebPart ( the one that you are seeing) was added to it and so the current _renderWebPart in master has different logic than the _renderWebPartOld. Because you only have _renderWebPart that means that you still have the older code.

**Comment by db3005** [comment]
@kemesfun I could find the _renderWebpartOld Method in the sp-pages-assembly file. At least in Firefox I could add a breakpoint and the method will be executed. How can we fix this?

![image](https://user-images.githubusercontent.com/32265743/78324828-1c52ca80-7576-11ea-99f2-59d9edf6125c.png)

**Comment by kemesfun** [comment]
@db3005 what stage is your farm, that your tenant is in, on? I want to confirm that the flight stage equals your farm stage.

**Comment by db3005** [comment]
@kemesfun its a pre release tenant:

![image](https://user-images.githubusercontent.com/32265743/78531038-026aef00-77e5-11ea-96d8-1d566fcf4f8b.png)

**Comment by OliverZeiser** [comment]
I am seeing the same issue. But on the same tenant, sometimes it works and sometimes it does not. But when adding this URL as an Iframe e.g. as a MS Teams Tab, then I can reproduce the issue every time.
Not sure if that helps to track down the issue, but it seems to be consistent and reproducable when the layouts Page is beeing displayed in an iframe.

**Comment by kemesfun** [comment]
What seems to be the case is that the flight doesn't hit all tenants. We will be making changes to solve this issue since the flight will take a while to get approved and reach all tenants.

**Comment by OliverZeiser** [comment]
@kemesfun Will that fix also work when hosting appPageHost.aspx in an iframe? Do you have any estimate time when this fix will be deployed worldwide?

**Comment by kemesfun** [comment]
@OliverZeiser yes it should work in an iFrame. The fix has been made, and will come out when our next rollout happens. I don't have a estimate time since rollouts can't be halted for various reasons.
