### ISSUE TITLE
Microsoft Teams Personal SPFX app throws popup with verify your identity 

### ISSUE THREAD

**Issue by joebergqvist** [SharePoint/sp-dev-docs#5686]
## Category

- [x] Bug
![2020-05-08 10_21_31-Teams](https://user-images.githubusercontent.com/12393122/81386696-bbd72000-9115-11ea-9d11-74b53a994dd9.png)

## Describe the bug

A personal tab / app built with SPFX v.10 published in tenant with graph api permissions granted tenant wide on SharePoint Online Client Extensibility Web Application Principal. 
The app has worked for several months in the tenant with no problems at all. Both in web and Teams client. 

2 days ago I started to get an annoying popup in the Teams client saying  "To view the information on this page, you need to verify your identity", I have never seen this popup before. The problem do not reside in browsers. I have seen this issue in one more tenant as well.

Every request seems to work fine, all data is loaded both from SharePoint and the Graph API. But The popup gets back on top over and over again. 

The issue seems to be sso getting broken (AADSTS50058), but this issue has been resolved with preAuthorizedApplications in the SharePoint Online Client Extensibility Web Application Principal Manifest before. 

Using fiddler I can get following information

`GET https://login.microsoftonline.com/54844b88-61b9-46ef-88af-cae5bd8a7087/oauth2/v2.0/authorize?response_type=id_token%20token&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default%20openid%20profile&client_id=cb0ea072-89d0-4bc6-bf3b-6759893263d3&redirect_uri=https%3A%2F%2Fxxxxxx.sharepoint.com%2F_forms%2Fspfxsinglesignon.aspx&state=fb5de9d4-00a1-4e35-b71f-015faab921c7&nonce=c47beee3-25ca-45bc-821c-01f9aa42f2b5&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.2.2&login_hint=username%40xxxxxx.se&client-request-id=7e264e3b-bc9d-48b6-bc17-08a15f7f962d&prompt=none&response_mode=fragment HTTP/1.1
Host: login.microsoftonline.com
Connection: keep-alive
`

`https://xxxxxxx.sharepoint.com/_forms/spfxsinglesignon.aspx#error=login_required&error_description=AADSTS50058%3a+A+silent+sign-in+request+was+sent+but+no+user+is+signed+in.%0d%0aTrace+ID%3a+a8878a79-cd88-45e3-8965-b142397b0900%0d%0aCorrelation+ID%3a+b2e32b23-bacd-471e-8afa-156f44df0879%0d%0aTimestamp%3a+2020-05-08+08%3a38%3a29Z&error_uri=https%3a%2f%2flogin.microsoftonline.com%2ferror%3fcode%3d50058&state=da71456e-0880-49dc-94b0-12d030905f9d`

In dev tools I can see pending network activity against 
`/_api/Microsoft.SharePoint.Internal.ClientSideComponent.Token.AcquireOBOToken?resource=%27https://graph.microsoft.com%27&clientId=%27cb0ea072-89d0-4bc6-bf3b-6759893263d3%27`

And in session storage: 

`AADSTS50058: A silent sign-in request was sent but no user is signed in.
Trace ID: 26531375-9d8f-4b05-bbfc-d33551ab0800
Correlation ID: f78cfe83-0c16-4beb-9c4f-9ced23bf19ad
Timestamp: 2020-05-08 08:35:54Z`

**The app is loaded with a manifest looking like this** 
    "staticTabs": [
        {
            "entityId": "tStart",
            "name": "Start",
            "contentUrl": "https://xxxxxx.sharepoint.com/sites/sitename/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=https://xxxxxx.sharepoint.com/sites/sitename/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId=1d45d922-c7b0-4f7c-bb49-22a01c8a2ec1%26forceLocale={locale}",
            "websiteUrl": "https://xxxxxx.sharepoint.com/sites/sitename",
            "scopes": [
                "personal"
            ]
        }
    ],
    "validDomains": [
        "*.login.microsoftonline.com",
        "*.sharepoint.com",
        "*.sharepoint-df.com",
        "spoppe-a.akamaihd.net",
        "spoprod-a.akamaihd.net",
        "resourceseng.blob.core.windows.net",
        "msft.spoppe.com"
    ],
    "webApplicationInfo":{
        "resource":"https://xxxxxx.sharepoint.com",
        "id":"00000003-0000-0ff1-ce00-000000000000"
     }
}

In the SharePoint Online Client Extensibility Web Application Principal | Manifest
`	"preAuthorizedApplications": [
		{
			"appId": "00000003-0000-0ff1-ce00-000000000000",
			"permissionIds": [
				"1c8df584-4c41-4deb-8d0b-1a331b5c3cb2"
			]
		}
	],`

## Environment details (*development & target environment*)

- **OS**: Seen behavior in both windows 10, macOS and mobile Teams Clients
- **Target Environment**:SharePoint Online
- **Tooling**: SPFx v1.10.0 

Thank you in advance and greatful for a quick response!

Kind regards J

**Comment by apollon7** [comment]
Same thing here. The popup appears since very short time for an app we have in use for several months now. The popup appears in Teams client (personal app), the data is still loaded. SPFX v1.10.

**Comment by primalairlabs** [comment]
Same here. It seems only to happen in the Teams App but not in Browser.

**Comment by OliverZeiser** [comment]
We are seeing the same thing now. We are also seeing this in sharepoint in the browser at some places: 
![image](https://user-images.githubusercontent.com/8672900/81531348-d18d5500-9362-11ea-8576-802126b1ee8d.png)
When reentering the credentials, nothing happens and the popup comes back again...

**Comment by OliverZeiser** [comment]
Okay, quick update: The problem in SharePoint could get resolved by resetting the browser. And for some reason it is gone in the teams client now as well.

**Comment by joebergqvist** [comment]
Thank you for your update Oliver!
**The problem still resides in Teams client**. Browsers works, like before as expected.
Error has been reported to MS support. But we have not been presented with any status or answer yet. 

Anyone else with any status of this issue? 

I have found following issue #4892 browsing github.

Microsoft, is this related? Have you rolled out any change during the past week that is causing this unexpected issue?

**Comment by adrichema** [comment]
We are also experiencing this issue in the Microsoft Teams client and only with calls that use the MSGraphClient. Calls that are using the AadHttpClient to are own API's seem to work just fine.

**Comment by joebergqvist** [comment]
I have used fiddler and compared two different setups with a test client. 
My own client has the latest build version 1.3.00.12058 (64-bit). Updated 2020-05-05
The test client has the build version 1.2.0.0.10168 (32-bit) Updated 2020-05-12
Same traffic and same issues AADSTS50058
**The difference is that the test client does not prompt with this alert.**

**Comment by adrichema** [comment]
Is it related to this issue? https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1612

**Comment by joebergqvist** [comment]
@primalairlabs  @apollon7  Do you have any updates on the popup problem?

**Comment by joebergqvist** [comment]
@andrewconnell I kindly reach out to you and hope you can find the time to look at this . have you seen any similar issues? Or heard about some ongoing bug?  
I have tried to create simple "hello world" WPs in different tenants. Using aadhttpclient or msgraphclient results in the silent sign in to fail and hence the annoying popup shows up. 
Its problematic if we need to do some workarounds instead of using the built in frameworks. 
As stated before, all api requests is  successful but the popup needs to be clicked once in a while to release the thread.

Thank you in advance!
Kind Regards J

**Comment by premakumaris** [comment]
HI All even we are facing the same issue, it works well in browser but having issue with teams client app. We are keep getting the pop up with error message saying "To view the information on this page, you need to verify your identity.". The issue appears for every call using the MSGraphClient for connecting to planner.

**Comment by giuleon** [comment]
I have the same experience, Has anyone tried to change the GUID of the webpart and reupload it in the catalog?

**Comment by VesaJuvonen** [comment]
We are closely looking into this as a priority. Sorry for the inconvenience.

**Comment by joebergqvist** [comment]
Good to hear @VesaJuvonen ! 
@giuleon I have tried alot of things. I have made simple new apps in other tenants as well. Using both aadhttpclient and msgraphclient this fails. Trusted sites and manifest changes and so on. The  only thing that seems to work as a bad interim right now is to cache the token ourself and make calls on our own without msgraphclient.

**Comment by VesaJuvonen** [comment]
Situation should be now resolved, so we would appreciated if anyone in this thread could double check the situation if you have a repro which you can use. Fix has been applied worldwide at this point, but would like to get your confirmation on this. Thanks for you assistance on this.

**Comment by tsaxfo** [comment]
> Situation should be now resolved, so we would appreciated if anyone in this thread could double check the situation if you have a repro which you can use. Fix has been applied worldwide at this point, but would like to get your confirmation on this. Thanks for you assistance on this.

I can confirm that it's working again! Thank you!

**Comment by joebergqvist** [comment]
> Situation should be now resolved, so we would appreciated if anyone in this thread could double check the situation if you have a repro which you can use. Fix has been applied worldwide at this point, but would like to get your confirmation on this. Thanks for you assistance on this.

Thank you @VesaJuvonen  everything works smooth again :) 
Do you care to share som details about what was wrong? 
I have been inside out for 10 days :D

Kind Regards Johan

**Comment by giuleon** [comment]
Not for me @VesaJuvonen, on Teams web version it works fine but opening the same personal app on Teams desktop app I receive the following error sniffed with Fiddler:

{"odata.error":{"code":"10001","message":{"lang":"en-US","value":"AADSTS65001: The user or administrator has not consented to use the application with ID '00000003-0000-0ff1-ce00-000000000000' named 'Office 365 SharePoint Online'. Send an interactive authorization request for this user and resource.\r\nTrace ID: 151fb0b1-e268-4de6-96bc-5bda559a4500\r\nCorrelation ID: e1b8539f-2059-b000-e134-7b7592f47a00\r\nTimestamp: 2020-05-18 20:02:18Z"},"error.redirectUrl":"https://*******.sharepoint.com/_layouts/15/teamshostedapp.aspx?teams&personal&componentId=bee408ef-3db3-403d-a67f-304353f73a49&forceLocale=en-gb&reauthid=2.MXwwfA.Ec3DKPGt_1Gm0AgMWs1ZN-HMd9g_wRCqE8mHvXyTBAa_hcOlKzafzb0cXy09HOQHTnlcwufWVnnBDZdKNQUaOVKmd2BCbeYGX9Jme0DV07h96Lap5WnjvuVywCoyZrMhJlOG2Ox14quvrQSLlBMYXzv31hcMwav9CML_F8LoYJ4l8UrgyzczjZzkSmTRlBnLR14FN5MiXIefw1EAI03uwnZgKeGmtahfxeESDgveQrAMTEqC_9jrdbcuHUkuiPJDc-Izt0e_ymB4Bhh6mgFT5Y8TH6Q1xxwrzp6gsFps1ie7gsg_gCzgVXPIJELAWoDMWoin7HxAXqtF6ywaL8A6kg"}}
0

at least the identity popup is disappeared

**Comment by joebergqvist** [comment]
@giuleon I am sure you have looked at the manifest for the SharePoint principal Aad app? Your issue Should be resolved with the following steps stated here: https://github.com/SharePoint/sp-dev-docs/issues/4013#issuecomment-499215940

This in combo with "webApplicationInfo":{
"resource":"https://xxxxxx.sharepoint.com",
"id":"00000003-0000-0ff1-ce00-000000000000"
} in your teams app manifest should be sufficient.

**Comment by giuleon** [comment]
@joebergqvist thanks for your help, seems like that you already faced the issue 😉.
I have already verified that this configuration in the "SharePoint Online Client Extensibility" differs between the two tenants, later I'll add the missing configuration in our production environment.
I'll provide feedback about the result

**Comment by giuleon** [comment]
I made the change on production by adding the JSON properties in the manifest (SharePoint Online Client Extensibility):
	"preAuthorizedApplications": [
		**{
			"appId": "00000003-0000-0ff1-ce00-000000000000",
			"permissionIds": [
				"xxxxxx-xxxxxx-xxxxx-xxxxx-xxxxxxxxxxx"
			]
		}**
	]

Now everything works fine, thanks again @VesaJuvonen and @joebergqvist for pointing me out on the issue.
I think we can close this one now

**Comment by VesaJuvonen** [comment]
thx @giuleon  for coming back and providing an update, highly appreciated.
