### ISSUE TITLE
SPFx 1.12 - gulp serve rebuilds new .js for every change

### ISSUE THREAD

**Issue by juliemturner** [SharePoint/sp-dev-docs#6838]
## Category

- [x] Bug

## Describe the bug

Testing a new 1.12 webpart and app customizer I'm finding that when gulp serve is running every change -- that triggers a rebuild -- is building a new version of the file (see attached screenshot). This is probably bad for a lot of reasons, but my reason is that it basically breaks the development process.

![image](https://user-images.githubusercontent.com/7570936/111825758-389e6300-88be-11eb-9046-c5e8bd68f7ba.png)

The cleanest and simplest way to do development of web parts and app customizers is to do a dev build (gulp clean & gulp bundle & gulp package-solution), deploy the resulting sppkg into your development tenant (I tend to use a site collection app catalog to isolate work), then put the web part on a page or make sure you've done skipFeatureDeployment for the app customizer, gulp serve --nobrowser your code and start working.  As long as you don't have to change packages, you're good to go.

Unfortunately, with this building different .js file for every change the changes are not picked up unless you stop gulp serve and restart it... 

## Steps to reproduce

1. Create a new SPFx solution (webpart or application customizer doesn't matter which)
1. Create a dev build (gulp clean & gulp bundle & gulp package-solution)
1. Deploy the resulting sppkg into your development tenant
1. `gulp serve --nobrowser` the solution
1. Add the application to a site collection.. if web part add it to a page
1. Make a modification to the code, new .js file is created in dist folder, but new .js file is not served, still serving old file.

## Expected behavior

Either dev server needs to update the file it serves or the file should not get a new name. Also, polluting the dist folder with multiple builds seems like a bad idea.

## Environment details (*development & target environment*)

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js v10.17.0
- **Browser(s)**: Chrome v89.0.4389.90
- **Tooling**: VS Code

### Additional context
None

**Comment by hoangbaophu89** [comment]
It is very inconvenient. In version 1.11 you can gulp serve and f5, your webpart will change.

Now every time the code changes, SPFX build always add 'contenthash' after name of js file, so webpart won't get the latest code.
You must : 
`gulp bundle `
`gulp package-solution`
upload to app catalog 
to get your new code, too many step for development.

In Development mode, I think we not add the append 'contenthash'  string, it only appears in Production mode.

**Comment by KevinTCoughlin** [comment]
We are validating a patch candidate that returns us to prior behavior. This was a regression for serve scenario. Thanks.

**Comment by VesaJuvonen** [comment]
This issue is intended to be part of the 1.2.1 patch release. Currently we recommend to keep on using 1.11 until further notice. We do apologize the inconvenience.

**Comment by Jerry0527** [comment]
Please rollback to v 1.11 as v1.12 has been deprecated:

![Snipaste_2021-03-25_17-48-10](https://user-images.githubusercontent.com/28797671/112453277-7bff4280-8d92-11eb-8c25-75eecb49bd1c.png)

**Comment by KevinTCoughlin** [comment]
@juliemturner can you confirm this "serve" issue is fixed in `1.12.1-rc.0` suite of packages e.g. https://www.npmjs.com/package/@microsoft/generator-sharepoint/v/1.12.1-rc.0?

**Comment by coreyroth** [comment]
@KevinTCoughlin with the tests on the other issue, I noticed that this issue still persists in RC0.

**Comment by KevinTCoughlin** [comment]
@coreyroth what command(s) did you run? When I run `gulp serve`, `dist` does not contain hashed JS and the local workbench reloads on change.

![image](https://user-images.githubusercontent.com/706967/114451908-a9b6fa80-9b8c-11eb-8d18-c555b035a685.png)

If you are experiencing `gulp bundle` producing hashed output, you should be using `gulp bundle --clean` to clean the `dist` directory.

**Comment by coreyroth** [comment]
@KevinTCoughlin it looks like what I am seeing is coming from gulp bundle.  I might actually be seeing another issue here (or something else that didn't get upgraded to rc0).  I'll post more or open another issue if necessary.

**Comment by juliemturner** [comment]
> @juliemturner can you confirm this "serve" issue is fixed in `1.12.1-rc.0` suite of packages e.g. https://www.npmjs.com/package/@microsoft/generator-sharepoint/v/1.12.1-rc.0?

@KevinTCoughlin - I am still seeing the issue, although it is different (and unfortunately worse) than it was previously as even if I start and stop the service, I cannot get my changes to load in the browser... I could research it more, but I think you'll see the same thing if you follow the steps I outlined in the original post, see "Steps to reproduce" -- to your above comment this issue never had anything to do with the workbench, although I get that the issue manifested itself there as well.

**Comment by s-KaiNet** [comment]
For me, the issue is resolved in `1.12.1-rc.0`. Now in `serve` mode it generates files without hashes.     

 @juliemturner @coreyroth are you running on `1.12.1-rc.0`? In the past I had problems with `nvm`, which somehow used the wrong SPFx generator version. Just check that in `.yo-rc.json` you have `"version": "1.12.1-rc.0",` and also in `package.json` corresponding package versions.

**Comment by coreyroth** [comment]
@s-KaiNet I updated the generator, my files in package.json, and .yo-rc.json.  I'm not using nvm at the moment.  I cleaned out release/assets since a lot of files got created by the issues in 1.12.0.  I noticed when I run gulp build, it only updated the manifest file once now after upgrading to rc0 and it doesn't update it any longer on subsequent builds so that's a step in the right direction.  However, I am seeing that the versions in the manifest files in release/assets has stayed at 1.12.0 whereas in a new project it says 1.12.1, so I am not sure what I missed.

**Comment by juliemturner** [comment]
@s-KaiNet -- yes I'm sure... And again this isn't only about the hash file names specifically although I see that that is probably fixed, the issue is still the one that I posted in the original issue, regardless of what got fixed.

**Comment by s-KaiNet** [comment]
@juliemturner you're right. `gulp serve` doesn't produce hashed files, however, `gulp bundle` ("dev" bundle) still produces them. That's a key difference between `1.11` and `1.12.1` - in `1.11` `gulp bundle` does not produce hashed files, thus no problem with debugging.

**Comment by juliemturner** [comment]
Unfortunately thought that may be the case I absolutely have a problem debugging because I can't use a dev build as described above... so to me this issue is not fixed.

**Comment by KevinTCoughlin** [comment]
I guess I got confused by the issue title mentioning `gulp serve` specifically. I will talk with the team about removing contenthash from output in non-ship bundle task e.g. `gulp bundle`.

**Comment by juliemturner** [comment]
@KevinTCoughlin assuming you are trying to fix the issue I submitted then this is about gulp serve. Can you please review the repo steps in the original issue as that issue still exists although originally it seemed the culprit for it was hash changing in the output it now is just fully broken and in my opinion worse than it was before as, what I call a development build (I.e. a build done without the --ship switch) and deployed to the app catalog should then load its code from localhost (and even says so from deployment) but now doesn't seem to be based on whatever is different from every previous build and this 1.12-rc0 release.

**Comment by andrewconnell** [comment]
I'm not sure if this #6897 is related @KevinTCoughlin ... seems pretty close to this issue but they aren't using 1.12, rather 1.11... thoughts?

**Comment by KevinTCoughlin** [comment]
> I'm not sure if this #6897 is related @KevinTCoughlin ... seems pretty close to this issue but they aren't using 1.12, rather 1.11... thoughts?

The content hash file name regression is scoped to the diff between SPFx `1.11` and `1.12`. We've identified the regression and latest `1.12.1-rc.3` currently publishing should resolve this issue.

**Comment by s-KaiNet** [comment]
For me `1.12.1-rc.3` now behaves exactly as `1.11` meaning that it doesn't generate hashed file names on `gulp bundle` and only emits them on production builds (`--ship`, `--production`).

**Comment by VesaJuvonen** [comment]
thx @s-KaiNet for confirming that the fix is working as expected.

**Comment by juliemturner** [comment]
I can confirm that the development build scenario that was described in the original issue is fixed in the rc3 release.

Thank you very much for your dedication to solving this critical issue.

**Comment by VesaJuvonen** [comment]
Thanks @juliemturner  for confirming that that fix was successful. We do not have any further known regressions with 1.12.1 and are looking into shipping it within upcoming days (not on weekend), if no new things are found.

Thanks everyone for your input on the new QA process and for validating the regressions. We'll use similar process also with all upcoming release to minimize regressions.

**Comment by KevinTCoughlin** [comment]
> I can confirm that the development build scenario that was described in the original issue is fixed in the rc3 release.
> 
> Thank you very much for your dedication to solving this critical issue.

Super! Thanks for reporting and validating.
