### ISSUE TITLE
SPFX Listview Command set doesn't work when searching with a library

### ISSUE THREAD

**Issue by ozippy** [SharePoint/sp-dev-docs#7133]
### What type of issue is this?

Question

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

I'm using Edge Version 92.0.902.30 (Official build) beta (64-bit) but I don't think it matters
- SPFx v1.11.0
- Node.js 10.15.3

### Issue description

Listview command sets do not seem to be visible in search results in a document library. They only work if you filter.

This is problematic for users in a large library because when they want to select a document and execute an action with a command set button, they cannot.

I have recorded a sample video demonstrating the behaviour.

https://user-images.githubusercontent.com/7800411/124064842-f4a02a00-da78-11eb-82ac-345ab6d6e877.mp4

Am I doing something wrong or is this a known issue? If it is known, is there any workaround or plan for future support?

Thanks

**Comment by AJIXuMuK** [comment]
Hi @ozippy,

Thanks for reporting this issue!
Sorry for the long delay. Could you please double check the behavior as it looks like fixed by now.

Thanks!

**Comment by ozippy** [comment]
Hi Alex, 

i just checked and the behaviour is still the same.

Thanks

**Comment by AJIXuMuK** [comment]
Hi @ozippy - thank you for the quick response.
Few additional questions as I'm unable to repro it:
1. Is this behavior happening on multiple tenants?
2. I assume you're using default command set provisioned by the generator, correct?
3. How are you testing the behavior:
    - debug query string + `gulp serve`
    - deployed debug solution + `gulp serve`
    - deployed released solution (`gulp bundle --ship`, `gulp package-solution --ship`)

**Comment by AJIXuMuK** [comment]
Hi @ozippy - this should be fixed WW by now. Could you please check in on your end?

Thanks!

**Comment by ozippy** [comment]
Hi Alex, that is awesome, thanks! It does seem to be working now.

Cheers

**Comment by AJIXuMuK** [comment]
Thank you for the confirmation!
