### ISSUE TITLE
App build in Spfx framework and deployed to team is not working on ios from today

### ISSUE THREAD

**Issue by harshdamaniahd** [SharePoint/sp-dev-docs#7311]
### What type of issue is this?

other

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Target SharePoint environment

SharePoint Online

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [X] mobile (iOS/iPadOS)
- [X] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version 1.10.0
- Node.js version 10.23.0
- etc

### Issue description

A Spfx solution deployed in teams, keeps loading in ios. It does work in android, desktop and web.
Have checked in other environment and getting the same issue.

**Comment by patmill** [comment]
Can you share any information, like what isn't working?  Can you share the versoin of the iOS teams app you are using?

**Comment by harshdamaniahd** [comment]
![image](https://user-images.githubusercontent.com/11780473/132811198-2e9f0775-aecc-4fd6-b479-dd6e996c471e.png)

An app created using spfx framework, get stuck and shows likes this
![image](https://user-images.githubusercontent.com/11780473/132811312-33700e2f-04f9-4f76-803e-88fd96f2190a.jpeg)


the other weird thing is that if i add a SharePoint page as an app in teams, then try opening spfx apps..they start working

**Comment by oyvindam** [comment]
FYI: Same issue has been reported in msteams-docs
https://github.com/MicrosoftDocs/msteams-docs/issues/4110

**Comment by harshdamaniahd** [comment]
I have found a solution to make it work for now. Same issue is raised on reddit forum has well

add the webpart on a sharepoint page first, then in manifest do the following 
![image](https://user-images.githubusercontent.com/11780473/133261245-10a70e07-9050-4ce9-8994-b907ad3cc016.png)

![image](https://user-images.githubusercontent.com/11780473/133261297-f75f3446-c521-4fb6-b889-467ecce89ef0.png)

**Comment by harshdamaniahd** [comment]
Hi, Still facing the issue, and it seems this has stopped working recently 
![image](https://user-images.githubusercontent.com/11780473/133266081-6fc04d23-c3a7-413b-9d78-2edb80a05a7d.png)

Quick observations,
Deploy any app in teams having just a sharepoint page in it, then you open the app which is not working. It will start working.
I believe there is authentication issue

**Comment by patmill** [comment]
Yes, we are aware of the auth issues - is there any chance that you can confirm that a basic app in teams written in SPFx that does not do additional authentication (ie, you are accessing non-SP data) works?

For apps written in SPFx hosted in the iOS teams app, we believe the fix has now rolled to 100% prod as of this morning.  Can you confirm?

**Comment by harshdamaniahd** [comment]
I have tested by just created a div using sharepoint framework, but it didn't work. It didn't have any additional authentication like graph sharepoint

**Comment by harshdamaniahd** [comment]
> Yes, we are aware of the auth issues - is there any chance that you can confirm that a basic app in teams written in SPFx that does not do additional authentication (ie, you are accessing non-SP data) works?
> 
> 
> 
> For apps written in SPFx hosted in the iOS teams app, we believe the fix has now rolled to 100% prod as of this morning.  Can you confirm?



any update on the fix:)

**Comment by cwdata** [comment]
Related problem here. A Teams app calling our own API using AadHttpClient works fine when started from Teams in a browser but it does not get the Auth token when started from within the Teams Desktop Client (Windows):
![image](https://user-images.githubusercontent.com/26869201/133992033-4147f2bb-d0f7-4ef7-9743-13977e0da9a0.png)

**Comment by harshdamaniahd** [comment]
seems like issue is resolved now. we can close this

**Comment by sharepointalist** [comment]
Still having this issue on multiple tenants. We do have both Graph and SharePoint authentication for our app.

**Comment by patmill** [comment]
@sharepointalist - Rather than keeping this bug open to track the graph auth issue (vs. the app load issue), I'm going to close this one.  Can you open a new one specifically around auth flows in iOS?

**Comment by harshdamaniahd** [comment]
Please re-open this issue as well. Stopped working from today again.
Also simple deployment of spfx webpart directly , by syncing it from sharepoint admin center doesnt work as well

**Comment by patmill** [comment]
So again, please don't reopen this issue, as it has all sorts context that is no longer applicable, etc.  Please open a new issue specific to what you are seeing.

**Comment by patmill** [comment]
@harshdamaniahd - can you confirm what exactly isn't working here for you?  Does the app not load / just spin in iOS?

**Comment by harshdamaniahd** [comment]
just spin in iOS.

But if I open a sharepoint page in teams or open the same app from viva connection it starts working.

The app only works if somehow a sharepoint page is opened first inside teams

**Comment by patmill** [comment]
Sorry - more clarifications.  Simple HelloWorld app (can't authenticate to the app to launch it)?  or an app that is doing token acquisition to an external API / AAD / Graph in an onInit phase (at which point, the app host has loaded, but the token fetch is failing)?

**Comment by harshdamaniahd** [comment]
Yes simple hello world webpart as well. It seems the code doesn't even reach unit.

But as soon as you open a sharepoint page, everything works, even graph query works

**Comment by GrahamMcMynn** [comment]
@harshdamaniahd  - can you check the current version of teams IOS?  Unfortunately this is fixed with our latest patch which is only available in 2021Sep-T1.  The August build does not have the fix in it, and that is the currently rolled out version.

**Comment by harshdamaniahd** [comment]
![image](https://user-images.githubusercontent.com/11780473/135674824-a21a36f3-5511-4035-b5c6-a8748888eccd.jpeg)

I don't see any updates on my App Store

**Comment by harshdamaniahd** [comment]
> @harshdamaniahd  - can you check the current version of teams IOS?  Unfortunately this is fixed with our latest patch which is only available in 2021Sep-T1.  The August build does not have the fix in it, and that is the currently rolled out version.  

When do you think the roll out will complete for everyone?
