### ISSUE TITLE
When property pane is in Non-Reactive mode, the validation function should only fire when clicked on "Apply"

### ISSUE THREAD

**Issue by vman** [SharePoint/sp-dev-docs#91]
Right now, no matter if in reactive or non-reactive mode, the validation function fires after the delay set in in the `deferredValidationTime` property (or the default 200 ms if the property is not set)

When in non-reactive mode, if the validation function fired only after the user clicked on "Apply", it would save a lot of unnecessary function calls, especially if the validation function is making an HTTP request somewhere (e.g. talking to SharePoint)

![function fire](https://cloud.githubusercontent.com/assets/173794/18028145/8de18674-6c6e-11e6-8a50-1a3ee98779ce.PNG)

My code for this is located here if it helps:
https://github.com/vman/SPFx-Web-part-property-validator

**Comment by patmill** [comment]
This should be fixed in Drop 2

**Comment by vman** [comment]
Looks like the issue is still present in Drop 2. Here is the code I have tried with:
https://github.com/vman/Drop-2-Validations

**Comment by srideshpande** [comment]
Hello @vman ,

Thanks for the feedback. I understand the problem with validation triggering on every key stroke. We have come up with a new feature which allows the developer to trigger the validation on blur(and also on focus). This new feature will soon be shipped, within a week or two.
Here are the two apis `validateOnFocusOut` and `validateOnFocusIn`.

Does this suffice your need for now? I know this is not triggering the validation on 'Apply' button click but definitely more helpful. Let us know your opinion.

**Comment by srideshpande** [comment]
Hello, @vman - Since I did not hear anything from you, I am closing the issue now. Please feel free to re-open it if you think the issue needs our further attention.

Thanks!

**Comment by vman** [comment]
Hi @srideshpande sorry I missed your message earlier. Thanks for the reply! I will have a look at it and get back to you on this.

**Comment by vman** [comment]
@srideshpande this works really well now. Great stuff!

**Comment by shahjinesh11** [comment]
@srideshpande I want to prepare some my custom code to manage other activities on apply. Can i do that? anything is available to execute on apply button?
