### ISSUE TITLE
ListView Command Set not loading when browse to the list from navigation

### ISSUE THREAD

**Issue by sosandumsft** [SharePoint/sp-dev-docs#9166]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [X] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version
- SPFx version
- Node.js version
- etc

### Describe the bug / error

When browsing to a list that has a Command Set from quick navigation it will not load the Command Set on initial load.
If you refresh the page it will load it.
Issue is not present if you browse direct to list (using view url) or if you start from site contents page.

### Steps to reproduce

1.Create an OOTB listview command set extension for lists and ContextMenu - https://learn.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api
2. Upload sppkg to tenant app catalog
3. Add the app to a team site
4. Create a simple list and add an item
5. Open an incognito browser session and browse to site
6. Using quick navigation go to list
7. Click on ContextMenu button - you will not see the commands
8. Refresh the page and click again on Contextmenu - commands will showing

### Expected behavior

We should see Commands of Command set from initial load of the list.

**Comment by sosandumsft** [comment]
The issue is not happening if you browse direct to list using view url (allitems.aspx) or when bgoing to list from Site Contents page. Also if you open list from navigation in a new tab it will work.

**Comment by nick-pape** [comment]
Thank you for this report. This sounds like a bug, so I've filed a ticket with product group to take a look at this further.

**Comment by sebastianmattar** [comment]
We also are experiencing this bug and are looking forward for a fix.

**Comment by sosandumsft** [comment]
A fix was made and it will be deployed in the next 10-12 days in Production.

**Comment by hesperanca** [comment]
We have been having on-and-off problems with command set extensions for over 1 year now. GitHub is also full of issues reported with command set extensions. They seem really unstable. I hope this will fix the issues once and for all.

**Comment by hesperanca** [comment]
Hi @VesaJuvonen. We are an ISV about to launch a new multi-tenant app that depends on Command set extensions. We have noticed that they seem to be really unstable, with this particular issue being reported as far back as 2019 (#4394). I've read your comments on #6611 but this issue is still a recurring issue. 

We need to know if we need to change our code to not depend on command set extensions (which would have a massive user experience impact) so it would be great if we could know what is being done to try to get to the root cause of the issue and try to fix it once and for all.

Many thanks.

**Comment by sosandumsft** [comment]
Looks like it was deployed to Prod and the issue is resolved.

**Comment by rgsteele** [comment]
I am still seeing this issue in our SharePoint Online tenant. Would this change take time to roll out worldwide, or is it possible the issue was not resolved?
