### ISSUE TITLE
SPFx ListView Command Set extension  in Microsoft Teams not working anymore

### ISSUE THREAD

**Issue by OliverZeiser** [SharePoint/sp-dev-docs#9275]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- Teams client as well as Teams in Browser
- SPFx version 1.17.3

### Describe the bug / error

ListView Command Set extension stopped working in SharePoint Document Libraries in Teams. They never worked in the Files tab, but they used to work in the "SharePoint" app when selecting a library. Something must have changed and they don't get loaded anymore. In SharePoint everything still works as expected.
Can we expect this feature to work again soon? BTW, why did this never work in the Files tab? This should be supported as well!

### Steps to reproduce

Create a listview command set extension, add it to a document library and try that inside of teams.

### Expected behavior

The commandset extensions should load and show up in the toolbar and context menue of the files.

**Comment by canturan** [comment]
Same problem here! We had at least a workaround to work with the "SharePoint" app, if we want to use the ListView Command Set extensions on the Teams but now it's gone. 
I also don't understand, why ListView Command Set extensions never worked on the Files tab in teams. It is very uncomfortable for the end user to switch to SharePoint just to use the Command Set. It just kills the Teams-Adoption.

**Comment by OliverZeiser** [comment]
@AJIXuMuK any updates on this one?

**Comment by penleychan** [comment]
Would also like to see this fixed.
It was supposably fixed in 2022 (https://github.com/SharePoint/sp-dev-docs/issues/5438) but that doesn't seem to be the case.

**Comment by Amey-MSFT** [comment]
Hello @OliverZeiser,
Thank you for bringing this issue to our attention. Could you please confirm if the issue still persists for you?

**Comment by OliverZeiser** [comment]
@Amey-MSFT yes it still exists. ListView Command Set extension still don't work in Teams

**Comment by Amey-MSFT** [comment]
Hello @OliverZeiser,
We were able to reproduce the issue, and we are investigating it. We have logged this as a bug, and our engineering team will look into it.
Thank you!

**Comment by Ashlesha-MSFT** [comment]
https://github.com/SharePoint/sp-dev-docs/issues/10140#issuecomment-3223429893
