### ISSUE TITLE
setValue not working in Microsoft Lists

### ISSUE THREAD

**Issue by Fedes365** [SharePoint/sp-dev-docs#9555]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version: Chrome 122.0.6261.95 (Official build) (64 bit)

### Describe the bug / error

**setValue** and all related capabilities are completely ignored in Microsoft Lists (browser version).

Conversely, in SharePoint user interface and Microsoft Lists PWA (Progressive Web App) everything works fine.

You can read about this bug also [here in Microsoft 365 PnP Repository](https://github.com/pnp/List-Formatting/issues/780), where a user reported that setValue was not working anymore as expected.

### Steps to reproduce

1. Create a new list
2. Open it through Microsoft List hub or add "_?env=WebViewList_" at the end of the URL
3. Add a Person type column
4. Add a new item
5. Apply a JSON column formatting to the person column created before. You can use this sample stored in Microsoft Official Repository on GitHub, to react and display users who have reacted to a specific item: https://raw.githubusercontent.com/pnp/List-Formatting/master/column-samples/multi-person-reaction/multi-person-reaction.json
6. setValue will not work as expected, being completely ignored by Microsoft Lists (browser version).

### Expected behavior

setValue should be recognized in Microsoft Lists so that "_formatters can render action buttons which modify the item internally without opening editors or forms_" as explained in Microsoft Learn website here: https://learn.microsoft.com/sharepoint/dev/declarative-customization/formatting-advanced#set-multiple-field-values-of-an-item-using-customrowaction

Here is a gif animation of the expected behaviour:

![setValue behaviour](https://github.com/SharePoint/sp-dev-docs/assets/95828495/eaea9d65-f5f9-4e0a-8c9b-6683ca2fcfa3)

**Comment by Synchh** [comment]
Just want to add that the error also occurs in Sharepoint for all users in our company (using both chrome and edge). See the attached video from our SharePoint environment.

Note one thing:
If "the multi-person reaction" already contained several registered people before the update, then one person can click several times in the cell and remove all registrations so that in the end it says "0" people. After that, nothing happens when you click in the cell, as the attached video shows.

https://app.screencast.com/x7WoNUzQqX8VJ

**Comment by tecchan1107** [comment]
Hi @Fedes365 @Synchh .
I saw a report on Twitter that the bug has been fixed. If you have time, could you please check it out?

**Comment by Synchh** [comment]
> Hi @Fedes365 @Synchh . I saw a report on Twitter that the bug has been fixed. If you have time, could you please check it out?

Hello

Unfortunately, it is not.

Lists converted to "new" lists still have the problem, as shown in the attached image. You can tell the difference between "new" lists and "old" lists based on standardized icons that come as part of the tab on new lists.

Old lists (without icon) work fine. I don't quite remember if old lists had the problem earlier when I first reported this and that these have now been fixed. But in all cases the problem occurs when the lists are converted to the new type of lists with an icon.

![Lists](https://github.com/SharePoint/sp-dev-docs/assets/161594120/7f3e1e3a-99e7-4126-936b-d4d1404f2af1)

**Comment by tecchan1107** [comment]
Thanks for checking @Synchh 🙏!!
Hmmm... I hope it gets fixed soon.... (And the new List is still not deployed in my environment... no icons are showing up)
![image](https://github.com/SharePoint/sp-dev-docs/assets/51254139/4b202159-6a48-4fb8-a437-2bfef93d90d5)

**Comment by Fedes365** [comment]
@tecchan1107 
Thanks! I've read that Twitter post just because you informed me about it 😅 I don't use Twitter often anymore, anyway I will test your sample again as soon as possible 👍

**Comment by Fedes365** [comment]
@tecchan1107 @Synchh 

still not working.

**Comment by Synchh** [comment]
Hi @Fedes365 and @tecchan1107, it looks like it's working again. Can you confirm ?

**Comment by tecchan1107** [comment]
Nice! Thanks for letting me know!
It worked fine in my environment! However, it is still an old list (?) in my environment😅 The icons are not displayed in the columns.

**Comment by Fedes365** [comment]
@tecchan1107 and @Synchh 

I confirm that it works in Microsoft Lists (browser) now.

I'll wait for a sp-dev-docs maintainer/responsible to consider this bug as officially solved and close it. In the meanwhile, I think it can stay open as a reference, in case any other user shall report problems about setValue.

Thanks for your contribution!

**Comment by Amey-MSFT** [comment]
Hello @Fedes365,
Thank you for bringing this issue to our attention. Could you please confirm if the issue still persists for you?
We will look into it and get back to you shortly.

**Comment by Fedes365** [comment]
@Amey-MSFT and @tecchan1107 

I've tested with this sample: https://github.com/pnp/List-Formatting/tree/master/column-samples/multi-person-reaction

From my testing, setValue is not working.

**Comment by Amey-MSFT** [comment]
Hello @Fedes365,
We were able to reproduce the issue, and we are investigating it. We have logged this as a bug, and our engineering team will look into it.
Thank you!

**Comment by Jeroen00** [comment]
@Amey-MSFT Is there an update on this? I just noticed that setValue is also no longer working on document library metadata. Code snippet below. This used to work...

` "customRowAction": {
            "action": "setValue",
            "actionInput": {
              "PromotedState": "=if(@currentField == 0, 2, 0)"
            }
          }
`
