### ISSUE TITLE
SP List Form configured with JSON fails to render multiple columns

### ISSUE THREAD

**Issue by anthonyg2003** [SharePoint/sp-dev-docs#9824]
When viewing a SharePoint List Item form, with JSON custom formatting applied to the body, the multiple-column display does not render when the browser viewport exceeds 1919px.

When viewport width > 1919px:
![image](https://github.com/user-attachments/assets/046854fc-e1e7-49db-9364-6c431ac3b3b5)

When viewport <=1919px:
![image](https://github.com/user-attachments/assets/36a50e9c-e14e-4d90-9bdf-bad93d1f24e7)

My screen is a 27" UHD in 3840 x 2160 resolution, and the rendered layout switches from multi-column to single-column when the browser's viewport width is greater than 1919px. 

Keeping the screen resolution the same, but changing the browser's viewport width by zooming the browser also will flip the multi-column rendering. I also changed the screen's resolutions to FHD and QHD with the same issue occurring at viewport width > 1919px. 

OS: Windows 11
Browser: Tested in Chrome and Edge (Version 127.0.2651.74)
SharePoint 365 Version: 16.0.0.25110

Here is gif showing the issue:

![SP List Form Multi-Column](https://github.com/user-attachments/assets/36d0c25c-a4e9-4006-b2fe-aa2d7903449e)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0f6aeedd-a76d-88b0-7ed5-93e20ac218bc
* Version Independent ID: 64315895-1103-d5f6-0195-9b5b61211132
* Content: [Configure the list form](https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-configuration)
* Content Source: [docs/declarative-customization/list-form-configuration.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/list-form-configuration.md)
* Service: **sharepoint-online**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

**Comment by jgupta-msft** [comment]
Thanks for reporting the issue. This has been fixed and should reach to prod in 2-3 weeks.

**Comment by ITensEI** [comment]
Been struggling to understand why the form won't display multiple columns no matter what I do for configuration. This issue is still happening. If the window is maximized, form will not display multiple columns unless the entire window is resized.

**Comment by Amey-MSFT** [comment]
Hello @anthonyg2003,
Thank You for your patience. Is the issue resolved now?

**Comment by Amey-MSFT** [comment]
We are closing this issue for now. If the problem persists, feel free to reopen it or open a new one.
