### ISSUE TITLE
SPFx solution cannot be built with HEFT tooling

### ISSUE THREAD

**Issue by ltdu** [SharePoint/sp-dev-docs#9942]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [ ] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [X] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- SPFx version: 1.20
- SPFx tooling version: 1.20.2
- Node.js version: 18.20.4

### Describe the bug / error

SharePoint Framework YO generator supports ```--use-heft``` parameter, which scaffolds solution to use HEFT instead of usual GULP. 
However, currently building such solution fails in ```webpack``` step:

```bash
 ---- build started ----
[build:clean] Deleted 0 files and 6 folders
[build:set-browserslist-ignore-old-data-env-var] Setting environment variable BROWSERSLIST_IGNORE_OLD_DATA=1
[build:sass] Generating sass typings...
[build:sass] Generated sass typings
[build:typescript] Using TypeScript version 5.3.3
[build:lint] Using ESLint version 8.57.0
[build:typescript] Copied 10 folders or files and linked 0 files
[build:webpack] Using Webpack version 5.88.2
[build:webpack] Running Webpack compilation
[build:webpack] Error: lib/webparts/helloWorld/HelloWorldWebPart.module.scss:1:0 - Module parse failed: Unexpected character '@' (1:0)
[build:webpack] You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
[build:webpack] > @import '~@microsoft/sp-office-ui-fabric-core/dist/sass/SPFabricCore.scss';
[build:webpack] |
[build:webpack] | .helloWorld {
 ---- build encountered an error (7.131s) ----
-------------------- Failed (7.14s) --------------------
Encountered 1 error
  [build:webpack] lib/webparts/helloWorld/HelloWorldWebPart.module.scss:1:0 - Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import '~@microsoft/sp-office-ui-fabric-core/dist/sass/SPFabricCore.scss';
|
| .helloWorld {
 ELIFECYCLE  Command failed with exit code 1.
```

As far as I can tell, problem originates in ```@microsoft/spfx-heft-plugins``` package. There is ```webpackConfigurationPlugin``` plugin which seems to be responsible for providing required configuration, including ```webpack``` loaders. I could find CSS loaders, but configuration seems broken:

```js
// @microsoft\spfx-heft-plugins\lib\plugins\webpackConfigurationPlugin\WebpackConfigurationGenerator.js (L:293)
{
    ...exports.COMMON_RULE_OPTIONS,
    use: moduleScssCssLoaders,
    test: /\.module\.scss\.css$/i
},
{
    ...exports.COMMON_RULE_OPTIONS,
    use: cssLoaders,
    test: /(?<!\.module(\.scss?))\.css$/
},
```

* neither of those regular expressions will pick ```*.module.scss``` for processing
* ```moduleScssCssLoaders``` and ```cssLoaders``` are essentially the same - they use ```@microsoft/sp-css-loader``` which does not have ```scss``` processing capability

### Steps to reproduce

1. Create new SPFx web part solution with HEFT support
```
yo @microsoft/sharepoint --use-heft
```
2. (Optional) Add TypeScript@5.3.3, because otherwise newer version maybe picked up which is not supported by used tools
```
npm install typescript@5.3.3 --save-dev --save-exact
```
3. Build
```
npm run build
```

### Expected behavior

Solution is built successfully

**Comment by stevebeauge** [comment]
@ltdu: this know for a while. I opened an issue 2 years later #9073 for the same issue, as some other did : https://github.com/SharePoint/sp-dev-docs/issues?q=is%3Aissue+heft+is%3Aopen

I don't think MS is willing to fix this. The spfx build chain is built on top of an incredible complex stack of outdated tools and I guess they're stuck. Hopefully they will move to a simpler toolchain eventually.

That said, heft is getting quite old, suffer from very long build time and an inexisting community ecosystem compared to more modern tools like turborepo or nx. Maybe you should consider moving out from heft? 

On our side we worked sucessfully with nx as build orchestrator and tsup (with a bunch of config) to build shared packages, if it can help

**Comment by Amey-MSFT** [comment]
Hello @ltdu ,
Thank You for your patience. Is the issue resolved now?

**Comment by ltdu** [comment]
Hi @Amey-MSFT ,

Unfortunately problem still remains. The other day I checked upcoming 1.21 version (1.21.0-beta.2) and issue is not yet fixed. Currently we are patching ```@microsoft/spfx-heft-plugins``` package manually, but it is definitely not a preferred solution.

**Comment by Amey-MSFT** [comment]
Ok @ltdu ,
We will look into it and get back to you shortly.

**Comment by Amey-MSFT** [comment]
Hello @ltdu ,
We were able to reproduce the issue, and we are investigating it. We have logged this as a bug, and our engineering team will look into it.
Thank you!

**Comment by jansenbe** [comment]
The next major SPFx release will officially support heft and the issue will be fixed there. We're closing this for now, if the problem still reproduces with the next SPFx release (1.22) then please re-open or create a new issue.

**Comment by jasmiendeclercq-svg** [comment]
Hi, can this be re-opened? I have the same issue with version 1.22.2

**Comment by stevebeauge** [comment]
@jasmiendeclercq-svg 

Because the toolchain has drastically changed, I guess you should open a new issue, with the exact details you are facing. MS folks are unlikely to reopen this very old issue, since it's probably a complete different root cause
