### ISSUE TITLE
List Formatting: Even if `hideSelction` is set to `true`, group header can still be selected

### ISSUE THREAD

**Issue by tecchan1107** [SharePoint/sp-dev-docs#9952]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

Declarative list formatting

### Developer environment

None

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Describe the bug / error

Even if `hideSelection` is set to `true`, the group header can still be selected. Additionally, when this setting is applied, the group header shifts to the right, causing the layout to appear broken.

![image](https://github.com/user-attachments/assets/90a22845-ac90-469e-bd85-a30abdf43b1c)

![microsoftlists](https://github.com/user-attachments/assets/cac6fd4a-c2f8-45cd-a893-2c5756bc6bc1)

### Steps to reproduce

1. Group by any column in any list
2. Apply the following JSON to the view formatting

    ``` json
    {
      "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/row-formatting.schema.json",
      "hideSelection": true
    }
    ``` 

### Expected behavior

If `hideSelection` is set to `true`, group header will not be selectable either.

**Comment by Fedes365** [comment]
@tecchan1107 

I can confirm these bugs from my side. Regarding the header shifting to the right (bug confirmed too), I'm using a workaround: the first column should be the OOTB "Type" one, so that the shift to the right will be minimal.

**Comment by jgupta-msft** [comment]
Thanks for reporting this issue. It has been fixed and should reach to prod in 2-3 weeks.

**Comment by XueSheng-GIT** [comment]
@jgupta-msft Thanks for the update. Since today `hideSelection` seems to work again.
But on the other side, the spacing in front of the group header and list items is still completely broken (as shown already in the initial report from @tecchan1107.

@tecchan1107 Maybe you can also double check from your side whether the issue is solved or (as I assume) only partly solved.

**Comment by tecchan1107** [comment]
Thanks for letting me know @XueSheng-GIT !

It was fixed in my environment, including the problem of the group header being shifted to the right.

![image](https://github.com/user-attachments/assets/91aa6514-c1d3-4a85-a7ee-a1944853edd0)

@XueSheng-GIT 
The content of the title of this issue was fixed, so I will close this issue. If the layout is not fixed in your environment, I am sorry, but please re-create a dedicated issue for it🙇‍♂️

**Comment by tecchan1107** [comment]
Thank you for the fix and responding @jgupta-msft !

**Comment by XueSheng-GIT** [comment]
> The content of the title of this issue was fixed, so I will close this issue. If the layout is not fixed in your environment, I am sorry, but please re-create a dedicated issue for it🙇‍♂️

Thanks for double checking, @tecchan1107.
The spacing issue still appears if `rowFormatter` is in use. Thus, created a new issue accordingly: https://github.com/SharePoint/sp-dev-docs/issues/9980

@jgupta-msft Can you have a look at this new issue which seems to be a regression.

**Comment by jgupta-msft** [comment]
Thanks. Looking at it
